// Code generated by ent, DO NOT EDIT.

package adminactionlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"oa.98ent.com/p9/core/rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLTE(FieldID, id))
}

// OperatorID applies equality check predicate on the "operator_id" field. It's identical to OperatorIDEQ.
func OperatorID(v int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldOperatorID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldUserID, v))
}

// RequestMethod applies equality check predicate on the "request_method" field. It's identical to RequestMethodEQ.
func RequestMethod(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldRequestMethod, v))
}

// RequestPath applies equality check predicate on the "request_path" field. It's identical to RequestPathEQ.
func RequestPath(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldRequestPath, v))
}

// RequestQuery applies equality check predicate on the "request_query" field. It's identical to RequestQueryEQ.
func RequestQuery(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldRequestQuery, v))
}

// RequestBody applies equality check predicate on the "request_body" field. It's identical to RequestBodyEQ.
func RequestBody(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldRequestBody, v))
}

// ActionResult applies equality check predicate on the "action_result" field. It's identical to ActionResultEQ.
func ActionResult(v int16) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldActionResult, v))
}

// ResponseStatus applies equality check predicate on the "response_status" field. It's identical to ResponseStatusEQ.
func ResponseStatus(v int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldResponseStatus, v))
}

// ResponseBody applies equality check predicate on the "response_body" field. It's identical to ResponseBodyEQ.
func ResponseBody(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldResponseBody, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldDurationMs, v))
}

// ClientIP applies equality check predicate on the "client_ip" field. It's identical to ClientIPEQ.
func ClientIP(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldClientIP, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldUserAgent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldCreatedAt, v))
}

// OperatorIDEQ applies the EQ predicate on the "operator_id" field.
func OperatorIDEQ(v int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorIDNEQ applies the NEQ predicate on the "operator_id" field.
func OperatorIDNEQ(v int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNEQ(FieldOperatorID, v))
}

// OperatorIDIn applies the In predicate on the "operator_id" field.
func OperatorIDIn(vs ...int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIn(FieldOperatorID, vs...))
}

// OperatorIDNotIn applies the NotIn predicate on the "operator_id" field.
func OperatorIDNotIn(vs ...int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotIn(FieldOperatorID, vs...))
}

// OperatorIDGT applies the GT predicate on the "operator_id" field.
func OperatorIDGT(v int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGT(FieldOperatorID, v))
}

// OperatorIDGTE applies the GTE predicate on the "operator_id" field.
func OperatorIDGTE(v int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGTE(FieldOperatorID, v))
}

// OperatorIDLT applies the LT predicate on the "operator_id" field.
func OperatorIDLT(v int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLT(FieldOperatorID, v))
}

// OperatorIDLTE applies the LTE predicate on the "operator_id" field.
func OperatorIDLTE(v int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLTE(FieldOperatorID, v))
}

// OperatorIDIsNil applies the IsNil predicate on the "operator_id" field.
func OperatorIDIsNil() predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIsNull(FieldOperatorID))
}

// OperatorIDNotNil applies the NotNil predicate on the "operator_id" field.
func OperatorIDNotNil() predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotNull(FieldOperatorID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotIn(FieldUserID, vs...))
}

// RequestMethodEQ applies the EQ predicate on the "request_method" field.
func RequestMethodEQ(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldRequestMethod, v))
}

// RequestMethodNEQ applies the NEQ predicate on the "request_method" field.
func RequestMethodNEQ(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNEQ(FieldRequestMethod, v))
}

// RequestMethodIn applies the In predicate on the "request_method" field.
func RequestMethodIn(vs ...string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIn(FieldRequestMethod, vs...))
}

// RequestMethodNotIn applies the NotIn predicate on the "request_method" field.
func RequestMethodNotIn(vs ...string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotIn(FieldRequestMethod, vs...))
}

// RequestMethodGT applies the GT predicate on the "request_method" field.
func RequestMethodGT(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGT(FieldRequestMethod, v))
}

// RequestMethodGTE applies the GTE predicate on the "request_method" field.
func RequestMethodGTE(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGTE(FieldRequestMethod, v))
}

// RequestMethodLT applies the LT predicate on the "request_method" field.
func RequestMethodLT(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLT(FieldRequestMethod, v))
}

// RequestMethodLTE applies the LTE predicate on the "request_method" field.
func RequestMethodLTE(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLTE(FieldRequestMethod, v))
}

// RequestMethodContains applies the Contains predicate on the "request_method" field.
func RequestMethodContains(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldContains(FieldRequestMethod, v))
}

// RequestMethodHasPrefix applies the HasPrefix predicate on the "request_method" field.
func RequestMethodHasPrefix(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldHasPrefix(FieldRequestMethod, v))
}

// RequestMethodHasSuffix applies the HasSuffix predicate on the "request_method" field.
func RequestMethodHasSuffix(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldHasSuffix(FieldRequestMethod, v))
}

// RequestMethodEqualFold applies the EqualFold predicate on the "request_method" field.
func RequestMethodEqualFold(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEqualFold(FieldRequestMethod, v))
}

// RequestMethodContainsFold applies the ContainsFold predicate on the "request_method" field.
func RequestMethodContainsFold(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldContainsFold(FieldRequestMethod, v))
}

// RequestPathEQ applies the EQ predicate on the "request_path" field.
func RequestPathEQ(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldRequestPath, v))
}

// RequestPathNEQ applies the NEQ predicate on the "request_path" field.
func RequestPathNEQ(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNEQ(FieldRequestPath, v))
}

// RequestPathIn applies the In predicate on the "request_path" field.
func RequestPathIn(vs ...string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIn(FieldRequestPath, vs...))
}

// RequestPathNotIn applies the NotIn predicate on the "request_path" field.
func RequestPathNotIn(vs ...string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotIn(FieldRequestPath, vs...))
}

// RequestPathGT applies the GT predicate on the "request_path" field.
func RequestPathGT(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGT(FieldRequestPath, v))
}

// RequestPathGTE applies the GTE predicate on the "request_path" field.
func RequestPathGTE(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGTE(FieldRequestPath, v))
}

// RequestPathLT applies the LT predicate on the "request_path" field.
func RequestPathLT(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLT(FieldRequestPath, v))
}

// RequestPathLTE applies the LTE predicate on the "request_path" field.
func RequestPathLTE(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLTE(FieldRequestPath, v))
}

// RequestPathContains applies the Contains predicate on the "request_path" field.
func RequestPathContains(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldContains(FieldRequestPath, v))
}

// RequestPathHasPrefix applies the HasPrefix predicate on the "request_path" field.
func RequestPathHasPrefix(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldHasPrefix(FieldRequestPath, v))
}

// RequestPathHasSuffix applies the HasSuffix predicate on the "request_path" field.
func RequestPathHasSuffix(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldHasSuffix(FieldRequestPath, v))
}

// RequestPathEqualFold applies the EqualFold predicate on the "request_path" field.
func RequestPathEqualFold(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEqualFold(FieldRequestPath, v))
}

// RequestPathContainsFold applies the ContainsFold predicate on the "request_path" field.
func RequestPathContainsFold(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldContainsFold(FieldRequestPath, v))
}

// RequestQueryEQ applies the EQ predicate on the "request_query" field.
func RequestQueryEQ(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldRequestQuery, v))
}

// RequestQueryNEQ applies the NEQ predicate on the "request_query" field.
func RequestQueryNEQ(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNEQ(FieldRequestQuery, v))
}

// RequestQueryIn applies the In predicate on the "request_query" field.
func RequestQueryIn(vs ...string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIn(FieldRequestQuery, vs...))
}

// RequestQueryNotIn applies the NotIn predicate on the "request_query" field.
func RequestQueryNotIn(vs ...string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotIn(FieldRequestQuery, vs...))
}

// RequestQueryGT applies the GT predicate on the "request_query" field.
func RequestQueryGT(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGT(FieldRequestQuery, v))
}

// RequestQueryGTE applies the GTE predicate on the "request_query" field.
func RequestQueryGTE(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGTE(FieldRequestQuery, v))
}

// RequestQueryLT applies the LT predicate on the "request_query" field.
func RequestQueryLT(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLT(FieldRequestQuery, v))
}

// RequestQueryLTE applies the LTE predicate on the "request_query" field.
func RequestQueryLTE(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLTE(FieldRequestQuery, v))
}

// RequestQueryContains applies the Contains predicate on the "request_query" field.
func RequestQueryContains(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldContains(FieldRequestQuery, v))
}

// RequestQueryHasPrefix applies the HasPrefix predicate on the "request_query" field.
func RequestQueryHasPrefix(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldHasPrefix(FieldRequestQuery, v))
}

// RequestQueryHasSuffix applies the HasSuffix predicate on the "request_query" field.
func RequestQueryHasSuffix(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldHasSuffix(FieldRequestQuery, v))
}

// RequestQueryIsNil applies the IsNil predicate on the "request_query" field.
func RequestQueryIsNil() predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIsNull(FieldRequestQuery))
}

// RequestQueryNotNil applies the NotNil predicate on the "request_query" field.
func RequestQueryNotNil() predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotNull(FieldRequestQuery))
}

// RequestQueryEqualFold applies the EqualFold predicate on the "request_query" field.
func RequestQueryEqualFold(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEqualFold(FieldRequestQuery, v))
}

// RequestQueryContainsFold applies the ContainsFold predicate on the "request_query" field.
func RequestQueryContainsFold(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldContainsFold(FieldRequestQuery, v))
}

// RequestBodyEQ applies the EQ predicate on the "request_body" field.
func RequestBodyEQ(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldRequestBody, v))
}

// RequestBodyNEQ applies the NEQ predicate on the "request_body" field.
func RequestBodyNEQ(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNEQ(FieldRequestBody, v))
}

// RequestBodyIn applies the In predicate on the "request_body" field.
func RequestBodyIn(vs ...string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIn(FieldRequestBody, vs...))
}

// RequestBodyNotIn applies the NotIn predicate on the "request_body" field.
func RequestBodyNotIn(vs ...string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotIn(FieldRequestBody, vs...))
}

// RequestBodyGT applies the GT predicate on the "request_body" field.
func RequestBodyGT(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGT(FieldRequestBody, v))
}

// RequestBodyGTE applies the GTE predicate on the "request_body" field.
func RequestBodyGTE(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGTE(FieldRequestBody, v))
}

// RequestBodyLT applies the LT predicate on the "request_body" field.
func RequestBodyLT(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLT(FieldRequestBody, v))
}

// RequestBodyLTE applies the LTE predicate on the "request_body" field.
func RequestBodyLTE(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLTE(FieldRequestBody, v))
}

// RequestBodyContains applies the Contains predicate on the "request_body" field.
func RequestBodyContains(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldContains(FieldRequestBody, v))
}

// RequestBodyHasPrefix applies the HasPrefix predicate on the "request_body" field.
func RequestBodyHasPrefix(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldHasPrefix(FieldRequestBody, v))
}

// RequestBodyHasSuffix applies the HasSuffix predicate on the "request_body" field.
func RequestBodyHasSuffix(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldHasSuffix(FieldRequestBody, v))
}

// RequestBodyIsNil applies the IsNil predicate on the "request_body" field.
func RequestBodyIsNil() predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIsNull(FieldRequestBody))
}

// RequestBodyNotNil applies the NotNil predicate on the "request_body" field.
func RequestBodyNotNil() predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotNull(FieldRequestBody))
}

// RequestBodyEqualFold applies the EqualFold predicate on the "request_body" field.
func RequestBodyEqualFold(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEqualFold(FieldRequestBody, v))
}

// RequestBodyContainsFold applies the ContainsFold predicate on the "request_body" field.
func RequestBodyContainsFold(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldContainsFold(FieldRequestBody, v))
}

// ActionResultEQ applies the EQ predicate on the "action_result" field.
func ActionResultEQ(v int16) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldActionResult, v))
}

// ActionResultNEQ applies the NEQ predicate on the "action_result" field.
func ActionResultNEQ(v int16) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNEQ(FieldActionResult, v))
}

// ActionResultIn applies the In predicate on the "action_result" field.
func ActionResultIn(vs ...int16) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIn(FieldActionResult, vs...))
}

// ActionResultNotIn applies the NotIn predicate on the "action_result" field.
func ActionResultNotIn(vs ...int16) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotIn(FieldActionResult, vs...))
}

// ActionResultGT applies the GT predicate on the "action_result" field.
func ActionResultGT(v int16) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGT(FieldActionResult, v))
}

// ActionResultGTE applies the GTE predicate on the "action_result" field.
func ActionResultGTE(v int16) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGTE(FieldActionResult, v))
}

// ActionResultLT applies the LT predicate on the "action_result" field.
func ActionResultLT(v int16) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLT(FieldActionResult, v))
}

// ActionResultLTE applies the LTE predicate on the "action_result" field.
func ActionResultLTE(v int16) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLTE(FieldActionResult, v))
}

// ResponseStatusEQ applies the EQ predicate on the "response_status" field.
func ResponseStatusEQ(v int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldResponseStatus, v))
}

// ResponseStatusNEQ applies the NEQ predicate on the "response_status" field.
func ResponseStatusNEQ(v int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNEQ(FieldResponseStatus, v))
}

// ResponseStatusIn applies the In predicate on the "response_status" field.
func ResponseStatusIn(vs ...int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIn(FieldResponseStatus, vs...))
}

// ResponseStatusNotIn applies the NotIn predicate on the "response_status" field.
func ResponseStatusNotIn(vs ...int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotIn(FieldResponseStatus, vs...))
}

// ResponseStatusGT applies the GT predicate on the "response_status" field.
func ResponseStatusGT(v int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGT(FieldResponseStatus, v))
}

// ResponseStatusGTE applies the GTE predicate on the "response_status" field.
func ResponseStatusGTE(v int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGTE(FieldResponseStatus, v))
}

// ResponseStatusLT applies the LT predicate on the "response_status" field.
func ResponseStatusLT(v int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLT(FieldResponseStatus, v))
}

// ResponseStatusLTE applies the LTE predicate on the "response_status" field.
func ResponseStatusLTE(v int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLTE(FieldResponseStatus, v))
}

// ResponseBodyEQ applies the EQ predicate on the "response_body" field.
func ResponseBodyEQ(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldResponseBody, v))
}

// ResponseBodyNEQ applies the NEQ predicate on the "response_body" field.
func ResponseBodyNEQ(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNEQ(FieldResponseBody, v))
}

// ResponseBodyIn applies the In predicate on the "response_body" field.
func ResponseBodyIn(vs ...string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIn(FieldResponseBody, vs...))
}

// ResponseBodyNotIn applies the NotIn predicate on the "response_body" field.
func ResponseBodyNotIn(vs ...string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotIn(FieldResponseBody, vs...))
}

// ResponseBodyGT applies the GT predicate on the "response_body" field.
func ResponseBodyGT(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGT(FieldResponseBody, v))
}

// ResponseBodyGTE applies the GTE predicate on the "response_body" field.
func ResponseBodyGTE(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGTE(FieldResponseBody, v))
}

// ResponseBodyLT applies the LT predicate on the "response_body" field.
func ResponseBodyLT(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLT(FieldResponseBody, v))
}

// ResponseBodyLTE applies the LTE predicate on the "response_body" field.
func ResponseBodyLTE(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLTE(FieldResponseBody, v))
}

// ResponseBodyContains applies the Contains predicate on the "response_body" field.
func ResponseBodyContains(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldContains(FieldResponseBody, v))
}

// ResponseBodyHasPrefix applies the HasPrefix predicate on the "response_body" field.
func ResponseBodyHasPrefix(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldHasPrefix(FieldResponseBody, v))
}

// ResponseBodyHasSuffix applies the HasSuffix predicate on the "response_body" field.
func ResponseBodyHasSuffix(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldHasSuffix(FieldResponseBody, v))
}

// ResponseBodyIsNil applies the IsNil predicate on the "response_body" field.
func ResponseBodyIsNil() predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIsNull(FieldResponseBody))
}

// ResponseBodyNotNil applies the NotNil predicate on the "response_body" field.
func ResponseBodyNotNil() predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotNull(FieldResponseBody))
}

// ResponseBodyEqualFold applies the EqualFold predicate on the "response_body" field.
func ResponseBodyEqualFold(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEqualFold(FieldResponseBody, v))
}

// ResponseBodyContainsFold applies the ContainsFold predicate on the "response_body" field.
func ResponseBodyContainsFold(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldContainsFold(FieldResponseBody, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLTE(FieldDurationMs, v))
}

// ClientIPEQ applies the EQ predicate on the "client_ip" field.
func ClientIPEQ(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldClientIP, v))
}

// ClientIPNEQ applies the NEQ predicate on the "client_ip" field.
func ClientIPNEQ(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNEQ(FieldClientIP, v))
}

// ClientIPIn applies the In predicate on the "client_ip" field.
func ClientIPIn(vs ...string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIn(FieldClientIP, vs...))
}

// ClientIPNotIn applies the NotIn predicate on the "client_ip" field.
func ClientIPNotIn(vs ...string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotIn(FieldClientIP, vs...))
}

// ClientIPGT applies the GT predicate on the "client_ip" field.
func ClientIPGT(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGT(FieldClientIP, v))
}

// ClientIPGTE applies the GTE predicate on the "client_ip" field.
func ClientIPGTE(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGTE(FieldClientIP, v))
}

// ClientIPLT applies the LT predicate on the "client_ip" field.
func ClientIPLT(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLT(FieldClientIP, v))
}

// ClientIPLTE applies the LTE predicate on the "client_ip" field.
func ClientIPLTE(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLTE(FieldClientIP, v))
}

// ClientIPContains applies the Contains predicate on the "client_ip" field.
func ClientIPContains(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldContains(FieldClientIP, v))
}

// ClientIPHasPrefix applies the HasPrefix predicate on the "client_ip" field.
func ClientIPHasPrefix(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldHasPrefix(FieldClientIP, v))
}

// ClientIPHasSuffix applies the HasSuffix predicate on the "client_ip" field.
func ClientIPHasSuffix(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldHasSuffix(FieldClientIP, v))
}

// ClientIPEqualFold applies the EqualFold predicate on the "client_ip" field.
func ClientIPEqualFold(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEqualFold(FieldClientIP, v))
}

// ClientIPContainsFold applies the ContainsFold predicate on the "client_ip" field.
func ClientIPContainsFold(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldContainsFold(FieldClientIP, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldContainsFold(FieldUserAgent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.AdminActionLog {
	return predicate.AdminActionLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.AdminActionLog {
	return predicate.AdminActionLog(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminActionLog) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminActionLog) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminActionLog) predicate.AdminActionLog {
	return predicate.AdminActionLog(sql.NotPredicates(p))
}
