// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_operator.proto

package operatordomainservice

import (
	"context"

	"oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc"

	"oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/domainpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OperatorDomainService interface {
		// 创建分站域名
		Create(ctx context.Context, in *domainpb.CreateDomainRequest, opts ...grpc.CallOption) (*domainpb.CreateDomainResponse, error)
		// 修改分站域名
		Update(ctx context.Context, in *domainpb.UpdateDomainRequest, opts ...grpc.CallOption) (*domainpb.UpdateDomainResponse, error)
		// 获取分站域名
		Get(ctx context.Context, in *domainpb.GetDomainRequest, opts ...grpc.CallOption) (*domainpb.GetDomainResponse, error)
		// 获取分站域名管理列表
		List(ctx context.Context, in *domainpb.ListDomainsRequest, opts ...grpc.CallOption) (*domainpb.ListDomainsResponse, error)
		// 删除分站域名
		Delete(ctx context.Context, in *domainpb.DeleteDomainRequest, opts ...grpc.CallOption) (*domainpb.DeleteDomainResponse, error)
	}

	defaultOperatorDomainService struct {
		cli zrpc.Client
	}
)

func NewOperatorDomainService(cli zrpc.Client) OperatorDomainService {
	return &defaultOperatorDomainService{
		cli: cli,
	}
}

// 创建分站域名
func (m *defaultOperatorDomainService) Create(ctx context.Context, in *domainpb.CreateDomainRequest, opts ...grpc.CallOption) (*domainpb.CreateDomainResponse, error) {
	client := platformoperatorrpc.NewOperatorDomainServiceClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

// 修改分站域名
func (m *defaultOperatorDomainService) Update(ctx context.Context, in *domainpb.UpdateDomainRequest, opts ...grpc.CallOption) (*domainpb.UpdateDomainResponse, error) {
	client := platformoperatorrpc.NewOperatorDomainServiceClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}

// 获取分站域名
func (m *defaultOperatorDomainService) Get(ctx context.Context, in *domainpb.GetDomainRequest, opts ...grpc.CallOption) (*domainpb.GetDomainResponse, error) {
	client := platformoperatorrpc.NewOperatorDomainServiceClient(m.cli.Conn())
	return client.Get(ctx, in, opts...)
}

// 获取分站域名管理列表
func (m *defaultOperatorDomainService) List(ctx context.Context, in *domainpb.ListDomainsRequest, opts ...grpc.CallOption) (*domainpb.ListDomainsResponse, error) {
	client := platformoperatorrpc.NewOperatorDomainServiceClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

// 删除分站域名
func (m *defaultOperatorDomainService) Delete(ctx context.Context, in *domainpb.DeleteDomainRequest, opts ...grpc.CallOption) (*domainpb.DeleteDomainResponse, error) {
	client := platformoperatorrpc.NewOperatorDomainServiceClient(m.cli.Conn())
	return client.Delete(ctx, in, opts...)
}
