// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package ent

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameCurrencyFieldNames          = builder.RawFieldNames(&GameCurrency{}, true)
	gameCurrencyRows                = strings.Join(gameCurrencyFieldNames, ",")
	gameCurrencyRowsExpectAutoSet   = strings.Join(stringx.Remove(gameCurrencyFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	gameCurrencyRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(gameCurrencyFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	gameCurrencyModel interface {
		Insert(ctx context.Context, data *GameCurrency) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GameCurrency, error)
		Update(ctx context.Context, data *GameCurrency) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGameCurrencyModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GameCurrency struct {
		Id           int64        `db:"id"`
		GameId       int64        `db:"game_id"`
		CurrencyId   int64        `db:"currency_id"`
		SourceStatus int64        `db:"source_status"`
		Status       int64        `db:"status"`
		DeletedAt    sql.NullTime `db:"deleted_at"`
		CreatedAt    time.Time    `db:"created_at"`
		UpdatedAt    time.Time    `db:"updated_at"`
	}
)

func newGameCurrencyModel(conn sqlx.SqlConn) *defaultGameCurrencyModel {
	return &defaultGameCurrencyModel{
		conn:  conn,
		table: `"public"."game_currency"`,
	}
}

func (m *defaultGameCurrencyModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGameCurrencyModel) FindOne(ctx context.Context, id int64) (*GameCurrency, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", gameCurrencyRows, m.table)
	var resp GameCurrency
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameCurrencyModel) Insert(ctx context.Context, data *GameCurrency) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, gameCurrencyRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.GameId, data.CurrencyId, data.SourceStatus, data.Status, data.DeletedAt)
	return ret, err
}

func (m *defaultGameCurrencyModel) Update(ctx context.Context, data *GameCurrency) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, gameCurrencyRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.GameId, data.CurrencyId, data.SourceStatus, data.Status, data.DeletedAt)
	return err
}

func (m *defaultGameCurrencyModel) tableName() string {
	return m.table
}
