// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/platform-game/rpc/ent/operatorgamecategory"
	"oa.98ent.com/p9/platform-game/rpc/ent/predicate"
)

// OperatorGameCategoryDelete is the builder for deleting a OperatorGameCategory entity.
type OperatorGameCategoryDelete struct {
	config
	hooks    []Hook
	mutation *OperatorGameCategoryMutation
}

// Where appends a list predicates to the OperatorGameCategoryDelete builder.
func (_d *OperatorGameCategoryDelete) Where(ps ...predicate.OperatorGameCategory) *OperatorGameCategoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OperatorGameCategoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OperatorGameCategoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OperatorGameCategoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(operatorgamecategory.Table, sqlgraph.NewFieldSpec(operatorgamecategory.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OperatorGameCategoryDeleteOne is the builder for deleting a single OperatorGameCategory entity.
type OperatorGameCategoryDeleteOne struct {
	_d *OperatorGameCategoryDelete
}

// Where appends a list predicates to the OperatorGameCategoryDelete builder.
func (_d *OperatorGameCategoryDeleteOne) Where(ps ...predicate.OperatorGameCategory) *OperatorGameCategoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OperatorGameCategoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{operatorgamecategory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OperatorGameCategoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
