// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/platform-game/rpc/ent/operatorgamechannel"
	"oa.98ent.com/p9/platform-game/rpc/ent/predicate"
)

// OperatorGameChannelDelete is the builder for deleting a OperatorGameChannel entity.
type OperatorGameChannelDelete struct {
	config
	hooks    []Hook
	mutation *OperatorGameChannelMutation
}

// Where appends a list predicates to the OperatorGameChannelDelete builder.
func (_d *OperatorGameChannelDelete) Where(ps ...predicate.OperatorGameChannel) *OperatorGameChannelDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OperatorGameChannelDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OperatorGameChannelDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OperatorGameChannelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(operatorgamechannel.Table, sqlgraph.NewFieldSpec(operatorgamechannel.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OperatorGameChannelDeleteOne is the builder for deleting a single OperatorGameChannel entity.
type OperatorGameChannelDeleteOne struct {
	_d *OperatorGameChannelDelete
}

// Where appends a list predicates to the OperatorGameChannelDelete builder.
func (_d *OperatorGameChannelDeleteOne) Where(ps ...predicate.OperatorGameChannel) *OperatorGameChannelDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OperatorGameChannelDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{operatorgamechannel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OperatorGameChannelDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
