// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/platform-operator/rpc/ent/operator"
	"oa.98ent.com/p9/platform-operator/rpc/ent/operatorlanguageallocation"
	"oa.98ent.com/p9/platform-operator/rpc/ent/predicate"
)

// OperatorLanguageAllocationUpdate is the builder for updating OperatorLanguageAllocation entities.
type OperatorLanguageAllocationUpdate struct {
	config
	hooks    []Hook
	mutation *OperatorLanguageAllocationMutation
}

// Where appends a list predicates to the OperatorLanguageAllocationUpdate builder.
func (_u *OperatorLanguageAllocationUpdate) Where(ps ...predicate.OperatorLanguageAllocation) *OperatorLanguageAllocationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAllocationStatus sets the "allocation_status" field.
func (_u *OperatorLanguageAllocationUpdate) SetAllocationStatus(v int64) *OperatorLanguageAllocationUpdate {
	_u.mutation.ResetAllocationStatus()
	_u.mutation.SetAllocationStatus(v)
	return _u
}

// SetNillableAllocationStatus sets the "allocation_status" field if the given value is not nil.
func (_u *OperatorLanguageAllocationUpdate) SetNillableAllocationStatus(v *int64) *OperatorLanguageAllocationUpdate {
	if v != nil {
		_u.SetAllocationStatus(*v)
	}
	return _u
}

// AddAllocationStatus adds value to the "allocation_status" field.
func (_u *OperatorLanguageAllocationUpdate) AddAllocationStatus(v int64) *OperatorLanguageAllocationUpdate {
	_u.mutation.AddAllocationStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OperatorLanguageAllocationUpdate) SetUpdatedAt(v time.Time) *OperatorLanguageAllocationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *OperatorLanguageAllocationUpdate) SetOperatorID(v int64) *OperatorLanguageAllocationUpdate {
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *OperatorLanguageAllocationUpdate) SetNillableOperatorID(v *int64) *OperatorLanguageAllocationUpdate {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// SetLanguageCode sets the "language_code" field.
func (_u *OperatorLanguageAllocationUpdate) SetLanguageCode(v string) *OperatorLanguageAllocationUpdate {
	_u.mutation.SetLanguageCode(v)
	return _u
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (_u *OperatorLanguageAllocationUpdate) SetNillableLanguageCode(v *string) *OperatorLanguageAllocationUpdate {
	if v != nil {
		_u.SetLanguageCode(*v)
	}
	return _u
}

// SetOperator sets the "operator" edge to the Operator entity.
func (_u *OperatorLanguageAllocationUpdate) SetOperator(v *Operator) *OperatorLanguageAllocationUpdate {
	return _u.SetOperatorID(v.ID)
}

// Mutation returns the OperatorLanguageAllocationMutation object of the builder.
func (_u *OperatorLanguageAllocationUpdate) Mutation() *OperatorLanguageAllocationMutation {
	return _u.mutation
}

// ClearOperator clears the "operator" edge to the Operator entity.
func (_u *OperatorLanguageAllocationUpdate) ClearOperator() *OperatorLanguageAllocationUpdate {
	_u.mutation.ClearOperator()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OperatorLanguageAllocationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OperatorLanguageAllocationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OperatorLanguageAllocationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OperatorLanguageAllocationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OperatorLanguageAllocationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := operatorlanguageallocation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OperatorLanguageAllocationUpdate) check() error {
	if v, ok := _u.mutation.AllocationStatus(); ok {
		if err := operatorlanguageallocation.AllocationStatusValidator(v); err != nil {
			return &ValidationError{Name: "allocation_status", err: fmt.Errorf(`ent: validator failed for field "OperatorLanguageAllocation.allocation_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LanguageCode(); ok {
		if err := operatorlanguageallocation.LanguageCodeValidator(v); err != nil {
			return &ValidationError{Name: "language_code", err: fmt.Errorf(`ent: validator failed for field "OperatorLanguageAllocation.language_code": %w`, err)}
		}
	}
	if _u.mutation.OperatorCleared() && len(_u.mutation.OperatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OperatorLanguageAllocation.operator"`)
	}
	return nil
}

func (_u *OperatorLanguageAllocationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(operatorlanguageallocation.Table, operatorlanguageallocation.Columns, sqlgraph.NewFieldSpec(operatorlanguageallocation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AllocationStatus(); ok {
		_spec.SetField(operatorlanguageallocation.FieldAllocationStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAllocationStatus(); ok {
		_spec.AddField(operatorlanguageallocation.FieldAllocationStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(operatorlanguageallocation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LanguageCode(); ok {
		_spec.SetField(operatorlanguageallocation.FieldLanguageCode, field.TypeString, value)
	}
	if _u.mutation.OperatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   operatorlanguageallocation.OperatorTable,
			Columns: []string{operatorlanguageallocation.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operator.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OperatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   operatorlanguageallocation.OperatorTable,
			Columns: []string{operatorlanguageallocation.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operator.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{operatorlanguageallocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OperatorLanguageAllocationUpdateOne is the builder for updating a single OperatorLanguageAllocation entity.
type OperatorLanguageAllocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OperatorLanguageAllocationMutation
}

// SetAllocationStatus sets the "allocation_status" field.
func (_u *OperatorLanguageAllocationUpdateOne) SetAllocationStatus(v int64) *OperatorLanguageAllocationUpdateOne {
	_u.mutation.ResetAllocationStatus()
	_u.mutation.SetAllocationStatus(v)
	return _u
}

// SetNillableAllocationStatus sets the "allocation_status" field if the given value is not nil.
func (_u *OperatorLanguageAllocationUpdateOne) SetNillableAllocationStatus(v *int64) *OperatorLanguageAllocationUpdateOne {
	if v != nil {
		_u.SetAllocationStatus(*v)
	}
	return _u
}

// AddAllocationStatus adds value to the "allocation_status" field.
func (_u *OperatorLanguageAllocationUpdateOne) AddAllocationStatus(v int64) *OperatorLanguageAllocationUpdateOne {
	_u.mutation.AddAllocationStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OperatorLanguageAllocationUpdateOne) SetUpdatedAt(v time.Time) *OperatorLanguageAllocationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *OperatorLanguageAllocationUpdateOne) SetOperatorID(v int64) *OperatorLanguageAllocationUpdateOne {
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *OperatorLanguageAllocationUpdateOne) SetNillableOperatorID(v *int64) *OperatorLanguageAllocationUpdateOne {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// SetLanguageCode sets the "language_code" field.
func (_u *OperatorLanguageAllocationUpdateOne) SetLanguageCode(v string) *OperatorLanguageAllocationUpdateOne {
	_u.mutation.SetLanguageCode(v)
	return _u
}

// SetNillableLanguageCode sets the "language_code" field if the given value is not nil.
func (_u *OperatorLanguageAllocationUpdateOne) SetNillableLanguageCode(v *string) *OperatorLanguageAllocationUpdateOne {
	if v != nil {
		_u.SetLanguageCode(*v)
	}
	return _u
}

// SetOperator sets the "operator" edge to the Operator entity.
func (_u *OperatorLanguageAllocationUpdateOne) SetOperator(v *Operator) *OperatorLanguageAllocationUpdateOne {
	return _u.SetOperatorID(v.ID)
}

// Mutation returns the OperatorLanguageAllocationMutation object of the builder.
func (_u *OperatorLanguageAllocationUpdateOne) Mutation() *OperatorLanguageAllocationMutation {
	return _u.mutation
}

// ClearOperator clears the "operator" edge to the Operator entity.
func (_u *OperatorLanguageAllocationUpdateOne) ClearOperator() *OperatorLanguageAllocationUpdateOne {
	_u.mutation.ClearOperator()
	return _u
}

// Where appends a list predicates to the OperatorLanguageAllocationUpdate builder.
func (_u *OperatorLanguageAllocationUpdateOne) Where(ps ...predicate.OperatorLanguageAllocation) *OperatorLanguageAllocationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OperatorLanguageAllocationUpdateOne) Select(field string, fields ...string) *OperatorLanguageAllocationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OperatorLanguageAllocation entity.
func (_u *OperatorLanguageAllocationUpdateOne) Save(ctx context.Context) (*OperatorLanguageAllocation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OperatorLanguageAllocationUpdateOne) SaveX(ctx context.Context) *OperatorLanguageAllocation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OperatorLanguageAllocationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OperatorLanguageAllocationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OperatorLanguageAllocationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := operatorlanguageallocation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OperatorLanguageAllocationUpdateOne) check() error {
	if v, ok := _u.mutation.AllocationStatus(); ok {
		if err := operatorlanguageallocation.AllocationStatusValidator(v); err != nil {
			return &ValidationError{Name: "allocation_status", err: fmt.Errorf(`ent: validator failed for field "OperatorLanguageAllocation.allocation_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LanguageCode(); ok {
		if err := operatorlanguageallocation.LanguageCodeValidator(v); err != nil {
			return &ValidationError{Name: "language_code", err: fmt.Errorf(`ent: validator failed for field "OperatorLanguageAllocation.language_code": %w`, err)}
		}
	}
	if _u.mutation.OperatorCleared() && len(_u.mutation.OperatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OperatorLanguageAllocation.operator"`)
	}
	return nil
}

func (_u *OperatorLanguageAllocationUpdateOne) sqlSave(ctx context.Context) (_node *OperatorLanguageAllocation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(operatorlanguageallocation.Table, operatorlanguageallocation.Columns, sqlgraph.NewFieldSpec(operatorlanguageallocation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OperatorLanguageAllocation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, operatorlanguageallocation.FieldID)
		for _, f := range fields {
			if !operatorlanguageallocation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != operatorlanguageallocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AllocationStatus(); ok {
		_spec.SetField(operatorlanguageallocation.FieldAllocationStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAllocationStatus(); ok {
		_spec.AddField(operatorlanguageallocation.FieldAllocationStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(operatorlanguageallocation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LanguageCode(); ok {
		_spec.SetField(operatorlanguageallocation.FieldLanguageCode, field.TypeString, value)
	}
	if _u.mutation.OperatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   operatorlanguageallocation.OperatorTable,
			Columns: []string{operatorlanguageallocation.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operator.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OperatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   operatorlanguageallocation.OperatorTable,
			Columns: []string{operatorlanguageallocation.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operator.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OperatorLanguageAllocation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{operatorlanguageallocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
