// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"oa.98ent.com/p9/platform-operator/rpc/ent/operator"
	"oa.98ent.com/p9/platform-operator/rpc/ent/operatorprofile"
)

// 总网 operator 档案表
type OperatorProfile struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID int64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 所属 operator 本地主键
	OperatorID int64 `json:"operator_id,omitempty"`
	// 公司名称
	CompanyName *string `json:"company_name,omitempty"`
	// 主要联系人名称
	ContactName *string `json:"contact_name,omitempty"`
	// 主要联系人邮箱
	ContactEmail *string `json:"contact_email,omitempty"`
	// 总网内部档案备注
	Remark *string `json:"remark,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OperatorProfileQuery when eager-loading is set.
	Edges        OperatorProfileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OperatorProfileEdges holds the relations/edges for other nodes in the graph.
type OperatorProfileEdges struct {
	// Operator holds the value of the operator edge.
	Operator *Operator `json:"operator,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OperatorOrErr returns the Operator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OperatorProfileEdges) OperatorOrErr() (*Operator, error) {
	if e.Operator != nil {
		return e.Operator, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: operator.Label}
	}
	return nil, &NotLoadedError{edge: "operator"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OperatorProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case operatorprofile.FieldID, operatorprofile.FieldOperatorID:
			values[i] = new(sql.NullInt64)
		case operatorprofile.FieldCompanyName, operatorprofile.FieldContactName, operatorprofile.FieldContactEmail, operatorprofile.FieldRemark:
			values[i] = new(sql.NullString)
		case operatorprofile.FieldCreatedAt, operatorprofile.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OperatorProfile fields.
func (_m *OperatorProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case operatorprofile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case operatorprofile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case operatorprofile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case operatorprofile.FieldOperatorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_id", values[i])
			} else if value.Valid {
				_m.OperatorID = value.Int64
			}
		case operatorprofile.FieldCompanyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field company_name", values[i])
			} else if value.Valid {
				_m.CompanyName = new(string)
				*_m.CompanyName = value.String
			}
		case operatorprofile.FieldContactName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_name", values[i])
			} else if value.Valid {
				_m.ContactName = new(string)
				*_m.ContactName = value.String
			}
		case operatorprofile.FieldContactEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_email", values[i])
			} else if value.Valid {
				_m.ContactEmail = new(string)
				*_m.ContactEmail = value.String
			}
		case operatorprofile.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OperatorProfile.
// This includes values selected through modifiers, order, etc.
func (_m *OperatorProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOperator queries the "operator" edge of the OperatorProfile entity.
func (_m *OperatorProfile) QueryOperator() *OperatorQuery {
	return NewOperatorProfileClient(_m.config).QueryOperator(_m)
}

// Update returns a builder for updating this OperatorProfile.
// Note that you need to call OperatorProfile.Unwrap() before calling this method if this OperatorProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OperatorProfile) Update() *OperatorProfileUpdateOne {
	return NewOperatorProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OperatorProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OperatorProfile) Unwrap() *OperatorProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OperatorProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OperatorProfile) String() string {
	var builder strings.Builder
	builder.WriteString("OperatorProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("operator_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OperatorID))
	builder.WriteString(", ")
	if v := _m.CompanyName; v != nil {
		builder.WriteString("company_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ContactName; v != nil {
		builder.WriteString("contact_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ContactEmail; v != nil {
		builder.WriteString("contact_email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// OperatorProfiles is a parsable slice of OperatorProfile.
type OperatorProfiles []*OperatorProfile
