-- 文件用途:
-- 用于维护 P9 平台支持的系统货币基础数据。
-- 货币编码作为全局唯一业务编码。
-- 金额统一按最小单位使用整数存储，通过 amount_factor 进行换算。
BEGIN;
  CREATE TABLE PUBLIC.currency (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- 货币全局唯一业务编码，例如 USD
    code VARCHAR (16) NOT NULL,
    -- 货币的多语言名称
    name_i18n JSONB NOT NULL,
    -- 货币类型: 1法定货币，2虚拟货币
    currency_type SMALLINT NOT NULL,
    -- 货币符号，例如 $、₱、₫
    symbol VARCHAR (16) NOT NULL,
    -- 金额换算倍率，例如 USD 为100，VND为1
    amount_factor BIGINT NOT NULL,
    -- 状态: 1启用，2停用
    status SMALLINT NOT NULL DEFAULT 1,
    -- 排序值，数值越小越靠前
    sort_no INTEGER NOT NULL DEFAULT 0,
    -- 创建时间
    created_at TIMESTAMPTZ (3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 更新时间
    updated_at TIMESTAMPTZ (3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_currency PRIMARY KEY (id),
    CONSTRAINT uk_currency_code UNIQUE (code)
  );
  COMMENT ON TABLE PUBLIC.currency IS '系统货币表';
  COMMENT ON COLUMN PUBLIC.currency.id IS '主键ID';
  COMMENT ON COLUMN PUBLIC.currency.code IS '货币编码';
  COMMENT ON COLUMN PUBLIC.currency.name_i18n IS '多语言名称';
  COMMENT ON COLUMN PUBLIC.currency.currency_type IS '货币类型: 1法定货币，2虚拟货币';
  COMMENT ON COLUMN PUBLIC.currency.symbol IS '货币符号';
  COMMENT ON COLUMN PUBLIC.currency.amount_factor IS '金额换算倍率';
  COMMENT ON COLUMN PUBLIC.currency.status IS '状态: 1启用，2停用';
  COMMENT ON COLUMN PUBLIC.currency.sort_no IS '排序值，数值越小越靠前';
  COMMENT ON COLUMN PUBLIC.currency.created_at IS '创建时间';
  COMMENT ON COLUMN PUBLIC.currency.updated_at IS '更新时间';
  INSERT INTO PUBLIC.currency (code, name_i18n, currency_type, symbol, amount_factor, status, sort_no)
  VALUES
  ('USD', '{ "zh-CN": "美元", "en-US": "US Dollar", "vi-VN": "Đô la Mỹ" }' :: JSONB, 1, '$', 100, 1, 10),
  ('PHP', '{ "zh-CN": "菲律宾比索", "en-US": "Philippine Peso", "vi-VN": "Peso Philippines" }' :: JSONB, 1, '₱', 100, 1, 20),
  ('VND', '{ "zh-CN": "越南盾", "en-US": "Vietnamese Dong", "vi-VN": "Đồng Việt Nam" }' :: JSONB, 1, '₫', 1, 1, 30),
  ('JPY', '{ "zh-CN": "日元", "en-US": "Japanese Yen", "vi-VN": "Yên Nhật" }' :: JSONB, 1, '¥', 1, 1, 40),
  ('MYR', '{ "zh-CN": "马来西亚林吉特", "en-US": "Malaysian Ringgit", "vi-VN": "Ringgit Malaysia" }' :: JSONB, 1, 'RM', 100, 1, 50),
  ('THB', '{ "zh-CN": "泰铢", "en-US": "Thai Baht", "vi-VN": "Baht Thái" }' :: JSONB, 1, '฿', 100, 1, 60),
  ('IDR', '{ "zh-CN": "印度尼西亚卢比", "en-US": "Indonesian Rupiah", "vi-VN": "Rupiah Indonesia" }' :: JSONB, 1, 'Rp', 1, 1, 70),
  ('SGD', '{ "zh-CN": "新加坡元", "en-US": "Singapore Dollar", "vi-VN": "Đô la Singapore" }' :: JSONB, 1, 'S$', 100, 1, 80),
  ('KRW', '{ "zh-CN": "韩元", "en-US": "South Korean Won", "vi-VN": "Won Hàn Quốc" }' :: JSONB, 1, '₩', 1, 1, 90),
  ('BRL', '{ "zh-CN": "巴西雷亚尔", "en-US": "Brazilian Real", "vi-VN": "Real Brazil" }' :: JSONB, 1, 'R$', 100, 1, 100),
  ('USDT', '{ "zh-CN": "泰达币", "en-US": "Tether", "vi-VN": "Tether" }' :: JSONB, 2, 'USDT', 100, 2, 110);
  COMMIT;