name: demo-core

services:
  postgres:
    image: postgres:18.6
    container_name: demo-core-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app123}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      TZ: Asia/Shanghai
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - p9-network

  redis:
    image: redis:8.8.0
    container_name: demo-core-redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - p9-network

  core-rpc:
    image: ${DOCKER_REPO:-192.168.0.15:5000/p9}/core-rpc:${VERSION:-1.0.0}
    container_name: demo-core-rpc
    restart: always
    ports:
      - "19000:19000"
    volumes:
      - ./etc/core-rpc.yaml:/app/etc/core.yaml:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - p9-network

  core-api:
    image: ${DOCKER_REPO:-192.168.0.15:5000/p9}/core-api:${VERSION:-1.0.0}
    container_name: demo-core-api
    restart: always
    ports:
      - "18000:18000"
    volumes:
      - ./etc/core-api.yaml:/app/etc/core.yaml:ro
    depends_on:
      - core-rpc
    networks:
      - p9-network

volumes:
  postgres_data:
  redis_data:

networks:
  p9-network:
    driver: bridge
