// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// API is the predicate function for api builders.
type API func(*sql.Selector)

// AdminActionLog is the predicate function for adminactionlog builders.
type AdminActionLog func(*sql.Selector)

// CasbinRule is the predicate function for casbinrule builders.
type CasbinRule func(*sql.Selector)

// ErrorLog is the predicate function for errorlog builders.
type ErrorLog func(*sql.Selector)

// LoginLog is the predicate function for loginlog builders.
type LoginLog func(*sql.Selector)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// Operator is the predicate function for operator builders.
type Operator func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
