// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/operator-base/rpc/ent/operator"
	"oa.98ent.com/p9/operator-base/rpc/ent/operatorlanguage"
)

// OperatorLanguageCreate is the builder for creating a OperatorLanguage entity.
type OperatorLanguageCreate struct {
	config
	mutation *OperatorLanguageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOperatorID sets the "operator_id" field.
func (_c *OperatorLanguageCreate) SetOperatorID(v int64) *OperatorLanguageCreate {
	_c.mutation.SetOperatorID(v)
	return _c
}

// SetLanguageCode sets the "language_code" field.
func (_c *OperatorLanguageCreate) SetLanguageCode(v string) *OperatorLanguageCreate {
	_c.mutation.SetLanguageCode(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OperatorLanguageCreate) SetCreatedAt(v time.Time) *OperatorLanguageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OperatorLanguageCreate) SetNillableCreatedAt(v *time.Time) *OperatorLanguageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OperatorLanguageCreate) SetID(v int64) *OperatorLanguageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetOperator sets the "operator" edge to the Operator entity.
func (_c *OperatorLanguageCreate) SetOperator(v *Operator) *OperatorLanguageCreate {
	return _c.SetOperatorID(v.ID)
}

// Mutation returns the OperatorLanguageMutation object of the builder.
func (_c *OperatorLanguageCreate) Mutation() *OperatorLanguageMutation {
	return _c.mutation
}

// Save creates the OperatorLanguage in the database.
func (_c *OperatorLanguageCreate) Save(ctx context.Context) (*OperatorLanguage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OperatorLanguageCreate) SaveX(ctx context.Context) *OperatorLanguage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OperatorLanguageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OperatorLanguageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OperatorLanguageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := operatorlanguage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OperatorLanguageCreate) check() error {
	if _, ok := _c.mutation.OperatorID(); !ok {
		return &ValidationError{Name: "operator_id", err: errors.New(`ent: missing required field "OperatorLanguage.operator_id"`)}
	}
	if _, ok := _c.mutation.LanguageCode(); !ok {
		return &ValidationError{Name: "language_code", err: errors.New(`ent: missing required field "OperatorLanguage.language_code"`)}
	}
	if v, ok := _c.mutation.LanguageCode(); ok {
		if err := operatorlanguage.LanguageCodeValidator(v); err != nil {
			return &ValidationError{Name: "language_code", err: fmt.Errorf(`ent: validator failed for field "OperatorLanguage.language_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OperatorLanguage.created_at"`)}
	}
	if len(_c.mutation.OperatorIDs()) == 0 {
		return &ValidationError{Name: "operator", err: errors.New(`ent: missing required edge "OperatorLanguage.operator"`)}
	}
	return nil
}

func (_c *OperatorLanguageCreate) sqlSave(ctx context.Context) (*OperatorLanguage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OperatorLanguageCreate) createSpec() (*OperatorLanguage, *sqlgraph.CreateSpec) {
	var (
		_node = &OperatorLanguage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(operatorlanguage.Table, sqlgraph.NewFieldSpec(operatorlanguage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.LanguageCode(); ok {
		_spec.SetField(operatorlanguage.FieldLanguageCode, field.TypeString, value)
		_node.LanguageCode = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(operatorlanguage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.OperatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   operatorlanguage.OperatorTable,
			Columns: []string{operatorlanguage.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operator.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OperatorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OperatorLanguage.Create().
//		SetOperatorID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OperatorLanguageUpsert) {
//			SetOperatorID(v+v).
//		}).
//		Exec(ctx)
func (_c *OperatorLanguageCreate) OnConflict(opts ...sql.ConflictOption) *OperatorLanguageUpsertOne {
	_c.conflict = opts
	return &OperatorLanguageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OperatorLanguage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OperatorLanguageCreate) OnConflictColumns(columns ...string) *OperatorLanguageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OperatorLanguageUpsertOne{
		create: _c,
	}
}

type (
	// OperatorLanguageUpsertOne is the builder for "upsert"-ing
	//  one OperatorLanguage node.
	OperatorLanguageUpsertOne struct {
		create *OperatorLanguageCreate
	}

	// OperatorLanguageUpsert is the "OnConflict" setter.
	OperatorLanguageUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OperatorLanguage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(operatorlanguage.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OperatorLanguageUpsertOne) UpdateNewValues() *OperatorLanguageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(operatorlanguage.FieldID)
		}
		if _, exists := u.create.mutation.OperatorID(); exists {
			s.SetIgnore(operatorlanguage.FieldOperatorID)
		}
		if _, exists := u.create.mutation.LanguageCode(); exists {
			s.SetIgnore(operatorlanguage.FieldLanguageCode)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(operatorlanguage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OperatorLanguage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OperatorLanguageUpsertOne) Ignore() *OperatorLanguageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OperatorLanguageUpsertOne) DoNothing() *OperatorLanguageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OperatorLanguageCreate.OnConflict
// documentation for more info.
func (u *OperatorLanguageUpsertOne) Update(set func(*OperatorLanguageUpsert)) *OperatorLanguageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OperatorLanguageUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *OperatorLanguageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OperatorLanguageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OperatorLanguageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OperatorLanguageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OperatorLanguageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OperatorLanguageCreateBulk is the builder for creating many OperatorLanguage entities in bulk.
type OperatorLanguageCreateBulk struct {
	config
	err      error
	builders []*OperatorLanguageCreate
	conflict []sql.ConflictOption
}

// Save creates the OperatorLanguage entities in the database.
func (_c *OperatorLanguageCreateBulk) Save(ctx context.Context) ([]*OperatorLanguage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OperatorLanguage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OperatorLanguageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OperatorLanguageCreateBulk) SaveX(ctx context.Context) []*OperatorLanguage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OperatorLanguageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OperatorLanguageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OperatorLanguage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OperatorLanguageUpsert) {
//			SetOperatorID(v+v).
//		}).
//		Exec(ctx)
func (_c *OperatorLanguageCreateBulk) OnConflict(opts ...sql.ConflictOption) *OperatorLanguageUpsertBulk {
	_c.conflict = opts
	return &OperatorLanguageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OperatorLanguage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OperatorLanguageCreateBulk) OnConflictColumns(columns ...string) *OperatorLanguageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OperatorLanguageUpsertBulk{
		create: _c,
	}
}

// OperatorLanguageUpsertBulk is the builder for "upsert"-ing
// a bulk of OperatorLanguage nodes.
type OperatorLanguageUpsertBulk struct {
	create *OperatorLanguageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OperatorLanguage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(operatorlanguage.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OperatorLanguageUpsertBulk) UpdateNewValues() *OperatorLanguageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(operatorlanguage.FieldID)
			}
			if _, exists := b.mutation.OperatorID(); exists {
				s.SetIgnore(operatorlanguage.FieldOperatorID)
			}
			if _, exists := b.mutation.LanguageCode(); exists {
				s.SetIgnore(operatorlanguage.FieldLanguageCode)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(operatorlanguage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OperatorLanguage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OperatorLanguageUpsertBulk) Ignore() *OperatorLanguageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OperatorLanguageUpsertBulk) DoNothing() *OperatorLanguageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OperatorLanguageCreateBulk.OnConflict
// documentation for more info.
func (u *OperatorLanguageUpsertBulk) Update(set func(*OperatorLanguageUpsert)) *OperatorLanguageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OperatorLanguageUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *OperatorLanguageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OperatorLanguageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OperatorLanguageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OperatorLanguageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
