// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/operator-base/rpc/ent/operator"
	"oa.98ent.com/p9/operator-base/rpc/ent/operatoragentline"
	"oa.98ent.com/p9/operator-base/rpc/ent/operatordomain"
	"oa.98ent.com/p9/operator-base/rpc/ent/operatorlanguage"
	"oa.98ent.com/p9/operator-base/rpc/ent/operatorregion"
)

// OperatorCreate is the builder for creating a Operator entity.
type OperatorCreate struct {
	config
	mutation *OperatorMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OperatorCreate) SetCreatedAt(v time.Time) *OperatorCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OperatorCreate) SetNillableCreatedAt(v *time.Time) *OperatorCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OperatorCreate) SetUpdatedAt(v time.Time) *OperatorCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OperatorCreate) SetNillableUpdatedAt(v *time.Time) *OperatorCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *OperatorCreate) SetCode(v string) *OperatorCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *OperatorCreate) SetName(v string) *OperatorCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTimezoneCode sets the "timezone_code" field.
func (_c *OperatorCreate) SetTimezoneCode(v string) *OperatorCreate {
	_c.mutation.SetTimezoneCode(v)
	return _c
}

// SetSettlementCurrencyCode sets the "settlement_currency_code" field.
func (_c *OperatorCreate) SetSettlementCurrencyCode(v string) *OperatorCreate {
	_c.mutation.SetSettlementCurrencyCode(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *OperatorCreate) SetStatus(v int64) *OperatorCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OperatorCreate) SetNillableStatus(v *int64) *OperatorCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OperatorCreate) SetID(v int64) *OperatorCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddDomainIDs adds the "domains" edge to the OperatorDomain entity by IDs.
func (_c *OperatorCreate) AddDomainIDs(ids ...int64) *OperatorCreate {
	_c.mutation.AddDomainIDs(ids...)
	return _c
}

// AddDomains adds the "domains" edges to the OperatorDomain entity.
func (_c *OperatorCreate) AddDomains(v ...*OperatorDomain) *OperatorCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDomainIDs(ids...)
}

// AddLanguageIDs adds the "languages" edge to the OperatorLanguage entity by IDs.
func (_c *OperatorCreate) AddLanguageIDs(ids ...int64) *OperatorCreate {
	_c.mutation.AddLanguageIDs(ids...)
	return _c
}

// AddLanguages adds the "languages" edges to the OperatorLanguage entity.
func (_c *OperatorCreate) AddLanguages(v ...*OperatorLanguage) *OperatorCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLanguageIDs(ids...)
}

// AddRegionIDs adds the "regions" edge to the OperatorRegion entity by IDs.
func (_c *OperatorCreate) AddRegionIDs(ids ...int64) *OperatorCreate {
	_c.mutation.AddRegionIDs(ids...)
	return _c
}

// AddRegions adds the "regions" edges to the OperatorRegion entity.
func (_c *OperatorCreate) AddRegions(v ...*OperatorRegion) *OperatorCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRegionIDs(ids...)
}

// AddAgentLineIDs adds the "agent_lines" edge to the OperatorAgentLine entity by IDs.
func (_c *OperatorCreate) AddAgentLineIDs(ids ...int64) *OperatorCreate {
	_c.mutation.AddAgentLineIDs(ids...)
	return _c
}

// AddAgentLines adds the "agent_lines" edges to the OperatorAgentLine entity.
func (_c *OperatorCreate) AddAgentLines(v ...*OperatorAgentLine) *OperatorCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAgentLineIDs(ids...)
}

// Mutation returns the OperatorMutation object of the builder.
func (_c *OperatorCreate) Mutation() *OperatorMutation {
	return _c.mutation
}

// Save creates the Operator in the database.
func (_c *OperatorCreate) Save(ctx context.Context) (*Operator, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OperatorCreate) SaveX(ctx context.Context) *Operator {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OperatorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OperatorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OperatorCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := operator.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := operator.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := operator.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OperatorCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Operator.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Operator.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Operator.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := operator.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Operator.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Operator.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := operator.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Operator.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TimezoneCode(); !ok {
		return &ValidationError{Name: "timezone_code", err: errors.New(`ent: missing required field "Operator.timezone_code"`)}
	}
	if v, ok := _c.mutation.TimezoneCode(); ok {
		if err := operator.TimezoneCodeValidator(v); err != nil {
			return &ValidationError{Name: "timezone_code", err: fmt.Errorf(`ent: validator failed for field "Operator.timezone_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SettlementCurrencyCode(); !ok {
		return &ValidationError{Name: "settlement_currency_code", err: errors.New(`ent: missing required field "Operator.settlement_currency_code"`)}
	}
	if v, ok := _c.mutation.SettlementCurrencyCode(); ok {
		if err := operator.SettlementCurrencyCodeValidator(v); err != nil {
			return &ValidationError{Name: "settlement_currency_code", err: fmt.Errorf(`ent: validator failed for field "Operator.settlement_currency_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Operator.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := operator.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Operator.status": %w`, err)}
		}
	}
	return nil
}

func (_c *OperatorCreate) sqlSave(ctx context.Context) (*Operator, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OperatorCreate) createSpec() (*Operator, *sqlgraph.CreateSpec) {
	var (
		_node = &Operator{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(operator.Table, sqlgraph.NewFieldSpec(operator.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(operator.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(operator.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(operator.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(operator.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.TimezoneCode(); ok {
		_spec.SetField(operator.FieldTimezoneCode, field.TypeString, value)
		_node.TimezoneCode = value
	}
	if value, ok := _c.mutation.SettlementCurrencyCode(); ok {
		_spec.SetField(operator.FieldSettlementCurrencyCode, field.TypeString, value)
		_node.SettlementCurrencyCode = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(operator.FieldStatus, field.TypeInt64, value)
		_node.Status = value
	}
	if nodes := _c.mutation.DomainsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   operator.DomainsTable,
			Columns: []string{operator.DomainsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operatordomain.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LanguagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   operator.LanguagesTable,
			Columns: []string{operator.LanguagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operatorlanguage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RegionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   operator.RegionsTable,
			Columns: []string{operator.RegionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operatorregion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AgentLinesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   operator.AgentLinesTable,
			Columns: []string{operator.AgentLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operatoragentline.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Operator.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OperatorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OperatorCreate) OnConflict(opts ...sql.ConflictOption) *OperatorUpsertOne {
	_c.conflict = opts
	return &OperatorUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Operator.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OperatorCreate) OnConflictColumns(columns ...string) *OperatorUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OperatorUpsertOne{
		create: _c,
	}
}

type (
	// OperatorUpsertOne is the builder for "upsert"-ing
	//  one Operator node.
	OperatorUpsertOne struct {
		create *OperatorCreate
	}

	// OperatorUpsert is the "OnConflict" setter.
	OperatorUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OperatorUpsert) SetUpdatedAt(v time.Time) *OperatorUpsert {
	u.Set(operator.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OperatorUpsert) UpdateUpdatedAt() *OperatorUpsert {
	u.SetExcluded(operator.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *OperatorUpsert) SetName(v string) *OperatorUpsert {
	u.Set(operator.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OperatorUpsert) UpdateName() *OperatorUpsert {
	u.SetExcluded(operator.FieldName)
	return u
}

// SetStatus sets the "status" field.
func (u *OperatorUpsert) SetStatus(v int64) *OperatorUpsert {
	u.Set(operator.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OperatorUpsert) UpdateStatus() *OperatorUpsert {
	u.SetExcluded(operator.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *OperatorUpsert) AddStatus(v int64) *OperatorUpsert {
	u.Add(operator.FieldStatus, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Operator.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(operator.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OperatorUpsertOne) UpdateNewValues() *OperatorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(operator.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(operator.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.Code(); exists {
			s.SetIgnore(operator.FieldCode)
		}
		if _, exists := u.create.mutation.TimezoneCode(); exists {
			s.SetIgnore(operator.FieldTimezoneCode)
		}
		if _, exists := u.create.mutation.SettlementCurrencyCode(); exists {
			s.SetIgnore(operator.FieldSettlementCurrencyCode)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Operator.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OperatorUpsertOne) Ignore() *OperatorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OperatorUpsertOne) DoNothing() *OperatorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OperatorCreate.OnConflict
// documentation for more info.
func (u *OperatorUpsertOne) Update(set func(*OperatorUpsert)) *OperatorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OperatorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OperatorUpsertOne) SetUpdatedAt(v time.Time) *OperatorUpsertOne {
	return u.Update(func(s *OperatorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OperatorUpsertOne) UpdateUpdatedAt() *OperatorUpsertOne {
	return u.Update(func(s *OperatorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *OperatorUpsertOne) SetName(v string) *OperatorUpsertOne {
	return u.Update(func(s *OperatorUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OperatorUpsertOne) UpdateName() *OperatorUpsertOne {
	return u.Update(func(s *OperatorUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *OperatorUpsertOne) SetStatus(v int64) *OperatorUpsertOne {
	return u.Update(func(s *OperatorUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *OperatorUpsertOne) AddStatus(v int64) *OperatorUpsertOne {
	return u.Update(func(s *OperatorUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OperatorUpsertOne) UpdateStatus() *OperatorUpsertOne {
	return u.Update(func(s *OperatorUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *OperatorUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OperatorCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OperatorUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OperatorUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OperatorUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OperatorCreateBulk is the builder for creating many Operator entities in bulk.
type OperatorCreateBulk struct {
	config
	err      error
	builders []*OperatorCreate
	conflict []sql.ConflictOption
}

// Save creates the Operator entities in the database.
func (_c *OperatorCreateBulk) Save(ctx context.Context) ([]*Operator, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Operator, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OperatorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OperatorCreateBulk) SaveX(ctx context.Context) []*Operator {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OperatorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OperatorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Operator.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OperatorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OperatorCreateBulk) OnConflict(opts ...sql.ConflictOption) *OperatorUpsertBulk {
	_c.conflict = opts
	return &OperatorUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Operator.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OperatorCreateBulk) OnConflictColumns(columns ...string) *OperatorUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OperatorUpsertBulk{
		create: _c,
	}
}

// OperatorUpsertBulk is the builder for "upsert"-ing
// a bulk of Operator nodes.
type OperatorUpsertBulk struct {
	create *OperatorCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Operator.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(operator.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OperatorUpsertBulk) UpdateNewValues() *OperatorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(operator.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(operator.FieldCreatedAt)
			}
			if _, exists := b.mutation.Code(); exists {
				s.SetIgnore(operator.FieldCode)
			}
			if _, exists := b.mutation.TimezoneCode(); exists {
				s.SetIgnore(operator.FieldTimezoneCode)
			}
			if _, exists := b.mutation.SettlementCurrencyCode(); exists {
				s.SetIgnore(operator.FieldSettlementCurrencyCode)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Operator.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OperatorUpsertBulk) Ignore() *OperatorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OperatorUpsertBulk) DoNothing() *OperatorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OperatorCreateBulk.OnConflict
// documentation for more info.
func (u *OperatorUpsertBulk) Update(set func(*OperatorUpsert)) *OperatorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OperatorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OperatorUpsertBulk) SetUpdatedAt(v time.Time) *OperatorUpsertBulk {
	return u.Update(func(s *OperatorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OperatorUpsertBulk) UpdateUpdatedAt() *OperatorUpsertBulk {
	return u.Update(func(s *OperatorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *OperatorUpsertBulk) SetName(v string) *OperatorUpsertBulk {
	return u.Update(func(s *OperatorUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OperatorUpsertBulk) UpdateName() *OperatorUpsertBulk {
	return u.Update(func(s *OperatorUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *OperatorUpsertBulk) SetStatus(v int64) *OperatorUpsertBulk {
	return u.Update(func(s *OperatorUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *OperatorUpsertBulk) AddStatus(v int64) *OperatorUpsertBulk {
	return u.Update(func(s *OperatorUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OperatorUpsertBulk) UpdateStatus() *OperatorUpsertBulk {
	return u.Update(func(s *OperatorUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *OperatorUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OperatorCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OperatorCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OperatorUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
