# API服务配置
Name: platform-base-api   # API服务名称
Host: 0.0.0.0             # API监听地址
Port: 18001               # API监听端口
Mode: dev                 # 运行模式

# Platform Base RPC配置
PlatformBaseRpc:
  Etcd:
    Hosts:
      - 192.168.0.15:2379   # Etcd地址
    Key: platform-base-rpc  # RPC服务注册Key

# Core RPC配置
CoreRpc:
  Endpoints:
    - platform-core-rpc:19000   # Core RPC地址
  NonBlock: true                # 非阻塞连接
  Timeout: 10000                # 请求超时时间, 毫秒

# 国际化配置
I18n:
  DefaultLanguage: zh-CN  # 默认语言