// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"oa.98ent.com/p9/core/rpc/ent/sysinit"
)

// Catalog init flag | 目录初始化标记
type SysInit struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key | 主键ID
	ID int64 `json:"id,omitempty"`
	// Created At | 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Updated At | 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Init category key | 初始化类别
	InitKey      string `json:"init_key,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysInit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysinit.FieldID:
			values[i] = new(sql.NullInt64)
		case sysinit.FieldInitKey:
			values[i] = new(sql.NullString)
		case sysinit.FieldCreatedAt, sysinit.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysInit fields.
func (_m *SysInit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysinit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case sysinit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sysinit.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sysinit.FieldInitKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field init_key", values[i])
			} else if value.Valid {
				_m.InitKey = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysInit.
// This includes values selected through modifiers, order, etc.
func (_m *SysInit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SysInit.
// Note that you need to call SysInit.Unwrap() before calling this method if this SysInit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysInit) Update() *SysInitUpdateOne {
	return NewSysInitClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysInit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysInit) Unwrap() *SysInit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysInit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysInit) String() string {
	var builder strings.Builder
	builder.WriteString("SysInit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("init_key=")
	builder.WriteString(_m.InitKey)
	builder.WriteByte(')')
	return builder.String()
}

// SysInits is a parsable slice of SysInit.
type SysInits []*SysInit
