syntax = "proto3";

package platform_operator;

option go_package = "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc";

import "types/platform_operator_ping.proto";
import "types/platform_operator_operator.proto";
import "types/platform_operator_profile.proto";
import "types/platform_operator_domain.proto";
import "types/platform_operator_admin.proto";
import "types/platform_operator_basic_resource_allocation.proto";
import "types/platform_operator_language_allocation.proto";
import "types/platform_operator_region_allocation.proto";
import "types/platform_operator_agent_line_allocation.proto";

// Ping 服务
service PingService {
  // Ping
  rpc Ping(platform_operator_ping.PingRequest) returns (platform_operator_ping.PingResponse);
}

// 分站服务
service OperatorService {
  // 创建分站
  rpc Create(platform_operator_operator.CreateOperatorRequest) returns (platform_operator_operator.CreateOperatorResponse);

  // 修改分站
  rpc Update(platform_operator_operator.UpdateOperatorRequest) returns (platform_operator_operator.UpdateOperatorResponse);

  // 获取分站
  rpc Get(platform_operator_operator.GetOperatorRequest) returns (platform_operator_operator.GetOperatorResponse);

  // 获取分站管理列表
  rpc List(platform_operator_operator.ListOperatorsRequest) returns (platform_operator_operator.ListOperatorsResponse);

  // 完成分站创建
  rpc Complete(platform_operator_operator.CompleteOperatorRequest) returns (platform_operator_operator.CompleteOperatorResponse);

  // 发布分站
  rpc Publish(platform_operator_operator.PublishOperatorRequest) returns (platform_operator_operator.PublishOperatorResponse);

  // 删除分站
  rpc Delete(platform_operator_operator.DeleteOperatorRequest) returns (platform_operator_operator.DeleteOperatorResponse);
}

// 分站档案服务
service OperatorProfileService {
  // 创建分站档案
  rpc Create(platform_operator_profile.CreateOperatorProfileRequest) returns (platform_operator_profile.CreateOperatorProfileResponse);

  // 修改分站档案
  rpc Update(platform_operator_profile.UpdateOperatorProfileRequest) returns (platform_operator_profile.UpdateOperatorProfileResponse);

  // 获取分站档案
  rpc Get(platform_operator_profile.GetOperatorProfileRequest) returns (platform_operator_profile.GetOperatorProfileResponse);
}

// 分站域名服务
service OperatorDomainService {
  // 创建分站域名
  rpc Create(platform_operator_domain.CreateDomainRequest) returns (platform_operator_domain.CreateDomainResponse);

  // 修改分站域名
  rpc Update(platform_operator_domain.UpdateDomainRequest) returns (platform_operator_domain.UpdateDomainResponse);

  // 获取分站域名
  rpc Get(platform_operator_domain.GetDomainRequest) returns (platform_operator_domain.GetDomainResponse);

  // 获取分站域名管理列表
  rpc List(platform_operator_domain.ListDomainsRequest) returns (platform_operator_domain.ListDomainsResponse);

  // 删除分站域名
  rpc Delete(platform_operator_domain.DeleteDomainRequest) returns (platform_operator_domain.DeleteDomainResponse);
}

// 分站管理员服务
service OperatorAdminService {
  // 创建分站管理员
  rpc Create(platform_operator_admin.CreateAdminRequest) returns (platform_operator_admin.CreateAdminResponse);

  // 获取分站管理员列表
  rpc List(platform_operator_admin.ListAdminsRequest) returns (platform_operator_admin.ListAdminsResponse);

  // 重置分站管理员密码
  rpc ResetPassword(platform_operator_admin.ResetAdminPasswordRequest) returns (platform_operator_admin.ResetAdminPasswordResponse);

  // 更新分站管理员
  rpc Update(platform_operator_admin.UpdateAdminRequest) returns (platform_operator_admin.UpdateAdminResponse);

  // 更新分站管理员状态
  rpc UpdateStatus(platform_operator_admin.UpdateAdminStatusRequest) returns (platform_operator_admin.UpdateAdminStatusResponse);

  // 按分站删除管理员
  rpc DeleteByOperatorId(platform_operator_admin.DeleteAdminsByOperatorIdRequest) returns (platform_operator_admin.DeleteAdminsByOperatorIdResponse);

  // 检测分站管理员是否已存在
  rpc ExistsByOperatorId(platform_operator_admin.ExistsAdminByOperatorIdRequest) returns (platform_operator_admin.ExistsAdminByOperatorIdResponse);

  // 获取分站管理员
  rpc Get(platform_operator_admin.GetAdminRequest) returns (platform_operator_admin.GetAdminResponse);
}

// 分站基础资源分配服务
service BasicResourceAllocationService {
  // 获取基础资源分配列表
  rpc List(platform_operator_basic_resource_allocation.ListBasicResourceAllocationsRequest) returns (platform_operator_basic_resource_allocation.ListBasicResourceAllocationsResponse);
}

// 分站语言分配服务
service LanguageAllocationService {
  // 获取语言分配列表
  rpc List(platform_operator_language_allocation.ListLanguageAllocationsRequest) returns (platform_operator_language_allocation.ListLanguageAllocationsResponse);

  // 保存语言分配
  rpc Save(platform_operator_language_allocation.SaveLanguageAllocationsRequest) returns (platform_operator_language_allocation.SaveLanguageAllocationsResponse);
}

// 分站经营地区分配服务
service RegionAllocationService {
  // 获取经营地区分配列表
  rpc List(platform_operator_region_allocation.ListRegionAllocationsRequest) returns (platform_operator_region_allocation.ListRegionAllocationsResponse);

  // 保存经营地区分配
  rpc Save(platform_operator_region_allocation.SaveRegionAllocationsRequest) returns (platform_operator_region_allocation.SaveRegionAllocationsResponse);
}

// 分站代理子线路分配服务
service AgentLineAllocationService {
  // 获取代理子线路分配列表
  rpc List(platform_operator_agent_line_allocation.ListAgentLineAllocationsRequest) returns (platform_operator_agent_line_allocation.ListAgentLineAllocationsResponse);

  // 保存代理子线路分配
  rpc Save(platform_operator_agent_line_allocation.SaveAgentLineAllocationsRequest) returns (platform_operator_agent_line_allocation.SaveAgentLineAllocationsResponse);
}