syntax = "proto3";

package platform_operator;

option go_package = "oa.98ent.com/p9/platform-operator/rpc/pb/operator";

import "types/ping.proto";
import "types/operator.proto";
import "types/profile.proto";
import "types/domain.proto";
import "types/language_allocation.proto";
import "types/region_allocation.proto";
import "types/agent_line_allocation.proto";

// Ping 服务
service PingService {
  // Ping
  rpc Ping(ping.PingRequest) returns (ping.PingResponse);
}

// 分站服务
service OperatorService {
  // 创建分站
  rpc Create(operator.CreateOperatorRequest) returns (operator.CreateOperatorResponse);

  // 修改分站
  rpc Update(operator.UpdateOperatorRequest) returns (operator.UpdateOperatorResponse);

  // 获取分站
  rpc Get(operator.GetOperatorRequest) returns (operator.GetOperatorResponse);

  // 获取分站管理列表
  rpc List(operator.ListOperatorsRequest) returns (operator.ListOperatorsResponse);

  // 完成分站创建
  rpc Complete(operator.CompleteOperatorRequest) returns (operator.CompleteOperatorResponse);

  // 发布分站
  rpc Publish(operator.PublishOperatorRequest) returns (operator.PublishOperatorResponse);
}

// 分站档案服务
service OperatorProfileService {
  // 创建分站档案
  rpc Create(profile.CreateOperatorProfileRequest) returns (profile.CreateOperatorProfileResponse);

  // 修改分站档案
  rpc Update(profile.UpdateOperatorProfileRequest) returns (profile.UpdateOperatorProfileResponse);

  // 获取分站档案
  rpc Get(profile.GetOperatorProfileRequest) returns (profile.GetOperatorProfileResponse);
}

// 分站域名服务
service DomainService {
  // 创建域名
  rpc Create(domain.CreateDomainRequest) returns (domain.CreateDomainResponse);

  // 修改域名
  rpc Update(domain.UpdateDomainRequest) returns (domain.UpdateDomainResponse);

  // 获取域名
  rpc Get(domain.GetDomainRequest) returns (domain.GetDomainResponse);

  // 获取域名管理列表
  rpc List(domain.ListDomainsRequest) returns (domain.ListDomainsResponse);

  // 删除域名
  rpc Delete(domain.DeleteDomainRequest) returns (domain.DeleteDomainResponse);
}

// 分站语言分配服务
service LanguageAllocationService {
  // 获取语言分配列表
  rpc List(languageallocation.ListLanguageAllocationsRequest) returns (languageallocation.ListLanguageAllocationsResponse);

  // 保存语言分配
  rpc Save(languageallocation.SaveLanguageAllocationsRequest) returns (languageallocation.SaveLanguageAllocationsResponse);
}

// 分站经营地区分配服务
service RegionAllocationService {
  // 获取经营地区分配列表
  rpc List(regionallocation.ListRegionAllocationsRequest) returns (regionallocation.ListRegionAllocationsResponse);

  // 保存经营地区分配
  rpc Save(regionallocation.SaveRegionAllocationsRequest) returns (regionallocation.SaveRegionAllocationsResponse);
}

// 分站代理子线路分配服务
service AgentLineAllocationService {
  // 获取代理子线路分配列表
  rpc List(agentlineallocation.ListAgentLineAllocationsRequest) returns (agentlineallocation.ListAgentLineAllocationsResponse);

  // 保存代理子线路分配
  rpc Save(agentlineallocation.SaveAgentLineAllocationsRequest) returns (agentlineallocation.SaveAgentLineAllocationsResponse);
}