// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_game.proto

package server

import (
	"context"

	"oa.98ent.com/p9/platform-game/rpc/internal/logic/operatorgameproviderservice"
	"oa.98ent.com/p9/platform-game/rpc/internal/svc"
	"oa.98ent.com/p9/platform-game/rpc/pb/platform_game"
)

type OperatorGameProviderServiceServer struct {
	svcCtx *svc.ServiceContext
	platform_game.UnimplementedOperatorGameProviderServiceServer
}

func NewOperatorGameProviderServiceServer(svcCtx *svc.ServiceContext) *OperatorGameProviderServiceServer {
	return &OperatorGameProviderServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取分站游戏提供商列表
func (s *OperatorGameProviderServiceServer) GetOperatorGameProviderList(ctx context.Context, in *platform_game.GetOperatorGameProviderListRequest) (*platform_game.GetOperatorGameProviderListResp, error) {
	l := operatorgameproviderservicelogic.NewGetOperatorGameProviderListLogic(ctx, s.svcCtx)
	return l.GetOperatorGameProviderList(in)
}

// 批量修改分站游戏提供商状态
func (s *OperatorGameProviderServiceServer) BatchUpdateOperatorGameProviderStatus(ctx context.Context, in *platform_game.BatchUpdateOperatorGameProviderStatusRequest) (*platform_game.BatchUpdateOperatorGameProviderStatusResp, error) {
	l := operatorgameproviderservicelogic.NewBatchUpdateOperatorGameProviderStatusLogic(ctx, s.svcCtx)
	return l.BatchUpdateOperatorGameProviderStatus(in)
}

// 保存分站游戏提供商分配
func (s *OperatorGameProviderServiceServer) SaveOperatorGameProviderAllocation(ctx context.Context, in *platform_game.SaveOperatorGameProviderAllocationRequest) (*platform_game.SaveOperatorGameProviderAllocationResp, error) {
	l := operatorgameproviderservicelogic.NewSaveOperatorGameProviderAllocationLogic(ctx, s.svcCtx)
	return l.SaveOperatorGameProviderAllocation(in)
}
