// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/node-dispatch/rpc/ent/dispatchtask"
	"oa.98ent.com/p9/node-dispatch/rpc/ent/dispatchtaskrun"
)

// DispatchTaskCreate is the builder for creating a DispatchTask entity.
type DispatchTaskCreate struct {
	config
	mutation *DispatchTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DispatchTaskCreate) SetCreatedAt(v time.Time) *DispatchTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DispatchTaskCreate) SetNillableCreatedAt(v *time.Time) *DispatchTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DispatchTaskCreate) SetUpdatedAt(v time.Time) *DispatchTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DispatchTaskCreate) SetNillableUpdatedAt(v *time.Time) *DispatchTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTaskNo sets the "task_no" field.
func (_c *DispatchTaskCreate) SetTaskNo(v string) *DispatchTaskCreate {
	_c.mutation.SetTaskNo(v)
	return _c
}

// SetRequestNo sets the "request_no" field.
func (_c *DispatchTaskCreate) SetRequestNo(v string) *DispatchTaskCreate {
	_c.mutation.SetRequestNo(v)
	return _c
}

// SetTarget sets the "target" field.
func (_c *DispatchTaskCreate) SetTarget(v string) *DispatchTaskCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetTaskType sets the "task_type" field.
func (_c *DispatchTaskCreate) SetTaskType(v string) *DispatchTaskCreate {
	_c.mutation.SetTaskType(v)
	return _c
}

// SetParams sets the "params" field.
func (_c *DispatchTaskCreate) SetParams(v json.RawMessage) *DispatchTaskCreate {
	_c.mutation.SetParams(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DispatchTaskCreate) SetStatus(v int64) *DispatchTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DispatchTaskCreate) SetNillableStatus(v *int64) *DispatchTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DispatchTaskCreate) SetID(v int64) *DispatchTaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddRunIDs adds the "runs" edge to the DispatchTaskRun entity by IDs.
func (_c *DispatchTaskCreate) AddRunIDs(ids ...int64) *DispatchTaskCreate {
	_c.mutation.AddRunIDs(ids...)
	return _c
}

// AddRuns adds the "runs" edges to the DispatchTaskRun entity.
func (_c *DispatchTaskCreate) AddRuns(v ...*DispatchTaskRun) *DispatchTaskCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRunIDs(ids...)
}

// Mutation returns the DispatchTaskMutation object of the builder.
func (_c *DispatchTaskCreate) Mutation() *DispatchTaskMutation {
	return _c.mutation
}

// Save creates the DispatchTask in the database.
func (_c *DispatchTaskCreate) Save(ctx context.Context) (*DispatchTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DispatchTaskCreate) SaveX(ctx context.Context) *DispatchTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DispatchTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DispatchTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DispatchTaskCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dispatchtask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dispatchtask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := dispatchtask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DispatchTaskCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DispatchTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DispatchTask.updated_at"`)}
	}
	if _, ok := _c.mutation.TaskNo(); !ok {
		return &ValidationError{Name: "task_no", err: errors.New(`ent: missing required field "DispatchTask.task_no"`)}
	}
	if v, ok := _c.mutation.TaskNo(); ok {
		if err := dispatchtask.TaskNoValidator(v); err != nil {
			return &ValidationError{Name: "task_no", err: fmt.Errorf(`ent: validator failed for field "DispatchTask.task_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestNo(); !ok {
		return &ValidationError{Name: "request_no", err: errors.New(`ent: missing required field "DispatchTask.request_no"`)}
	}
	if v, ok := _c.mutation.RequestNo(); ok {
		if err := dispatchtask.RequestNoValidator(v); err != nil {
			return &ValidationError{Name: "request_no", err: fmt.Errorf(`ent: validator failed for field "DispatchTask.request_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "DispatchTask.target"`)}
	}
	if v, ok := _c.mutation.Target(); ok {
		if err := dispatchtask.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "DispatchTask.target": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaskType(); !ok {
		return &ValidationError{Name: "task_type", err: errors.New(`ent: missing required field "DispatchTask.task_type"`)}
	}
	if v, ok := _c.mutation.TaskType(); ok {
		if err := dispatchtask.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "DispatchTask.task_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Params(); !ok {
		return &ValidationError{Name: "params", err: errors.New(`ent: missing required field "DispatchTask.params"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DispatchTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := dispatchtask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DispatchTask.status": %w`, err)}
		}
	}
	return nil
}

func (_c *DispatchTaskCreate) sqlSave(ctx context.Context) (*DispatchTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DispatchTaskCreate) createSpec() (*DispatchTask, *sqlgraph.CreateSpec) {
	var (
		_node = &DispatchTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dispatchtask.Table, sqlgraph.NewFieldSpec(dispatchtask.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dispatchtask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dispatchtask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TaskNo(); ok {
		_spec.SetField(dispatchtask.FieldTaskNo, field.TypeString, value)
		_node.TaskNo = value
	}
	if value, ok := _c.mutation.RequestNo(); ok {
		_spec.SetField(dispatchtask.FieldRequestNo, field.TypeString, value)
		_node.RequestNo = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(dispatchtask.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.TaskType(); ok {
		_spec.SetField(dispatchtask.FieldTaskType, field.TypeString, value)
		_node.TaskType = value
	}
	if value, ok := _c.mutation.Params(); ok {
		_spec.SetField(dispatchtask.FieldParams, field.TypeJSON, value)
		_node.Params = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(dispatchtask.FieldStatus, field.TypeInt64, value)
		_node.Status = value
	}
	if nodes := _c.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dispatchtask.RunsTable,
			Columns: []string{dispatchtask.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dispatchtaskrun.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DispatchTask.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DispatchTaskUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DispatchTaskCreate) OnConflict(opts ...sql.ConflictOption) *DispatchTaskUpsertOne {
	_c.conflict = opts
	return &DispatchTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DispatchTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DispatchTaskCreate) OnConflictColumns(columns ...string) *DispatchTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DispatchTaskUpsertOne{
		create: _c,
	}
}

type (
	// DispatchTaskUpsertOne is the builder for "upsert"-ing
	//  one DispatchTask node.
	DispatchTaskUpsertOne struct {
		create *DispatchTaskCreate
	}

	// DispatchTaskUpsert is the "OnConflict" setter.
	DispatchTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DispatchTaskUpsert) SetUpdatedAt(v time.Time) *DispatchTaskUpsert {
	u.Set(dispatchtask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DispatchTaskUpsert) UpdateUpdatedAt() *DispatchTaskUpsert {
	u.SetExcluded(dispatchtask.FieldUpdatedAt)
	return u
}

// SetStatus sets the "status" field.
func (u *DispatchTaskUpsert) SetStatus(v int64) *DispatchTaskUpsert {
	u.Set(dispatchtask.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DispatchTaskUpsert) UpdateStatus() *DispatchTaskUpsert {
	u.SetExcluded(dispatchtask.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *DispatchTaskUpsert) AddStatus(v int64) *DispatchTaskUpsert {
	u.Add(dispatchtask.FieldStatus, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DispatchTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dispatchtask.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DispatchTaskUpsertOne) UpdateNewValues() *DispatchTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(dispatchtask.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(dispatchtask.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TaskNo(); exists {
			s.SetIgnore(dispatchtask.FieldTaskNo)
		}
		if _, exists := u.create.mutation.RequestNo(); exists {
			s.SetIgnore(dispatchtask.FieldRequestNo)
		}
		if _, exists := u.create.mutation.Target(); exists {
			s.SetIgnore(dispatchtask.FieldTarget)
		}
		if _, exists := u.create.mutation.TaskType(); exists {
			s.SetIgnore(dispatchtask.FieldTaskType)
		}
		if _, exists := u.create.mutation.Params(); exists {
			s.SetIgnore(dispatchtask.FieldParams)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DispatchTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DispatchTaskUpsertOne) Ignore() *DispatchTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DispatchTaskUpsertOne) DoNothing() *DispatchTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DispatchTaskCreate.OnConflict
// documentation for more info.
func (u *DispatchTaskUpsertOne) Update(set func(*DispatchTaskUpsert)) *DispatchTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DispatchTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DispatchTaskUpsertOne) SetUpdatedAt(v time.Time) *DispatchTaskUpsertOne {
	return u.Update(func(s *DispatchTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DispatchTaskUpsertOne) UpdateUpdatedAt() *DispatchTaskUpsertOne {
	return u.Update(func(s *DispatchTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *DispatchTaskUpsertOne) SetStatus(v int64) *DispatchTaskUpsertOne {
	return u.Update(func(s *DispatchTaskUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *DispatchTaskUpsertOne) AddStatus(v int64) *DispatchTaskUpsertOne {
	return u.Update(func(s *DispatchTaskUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DispatchTaskUpsertOne) UpdateStatus() *DispatchTaskUpsertOne {
	return u.Update(func(s *DispatchTaskUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *DispatchTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DispatchTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DispatchTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DispatchTaskUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DispatchTaskUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DispatchTaskCreateBulk is the builder for creating many DispatchTask entities in bulk.
type DispatchTaskCreateBulk struct {
	config
	err      error
	builders []*DispatchTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the DispatchTask entities in the database.
func (_c *DispatchTaskCreateBulk) Save(ctx context.Context) ([]*DispatchTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DispatchTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DispatchTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DispatchTaskCreateBulk) SaveX(ctx context.Context) []*DispatchTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DispatchTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DispatchTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DispatchTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DispatchTaskUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DispatchTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *DispatchTaskUpsertBulk {
	_c.conflict = opts
	return &DispatchTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DispatchTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DispatchTaskCreateBulk) OnConflictColumns(columns ...string) *DispatchTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DispatchTaskUpsertBulk{
		create: _c,
	}
}

// DispatchTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of DispatchTask nodes.
type DispatchTaskUpsertBulk struct {
	create *DispatchTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DispatchTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dispatchtask.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DispatchTaskUpsertBulk) UpdateNewValues() *DispatchTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(dispatchtask.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(dispatchtask.FieldCreatedAt)
			}
			if _, exists := b.mutation.TaskNo(); exists {
				s.SetIgnore(dispatchtask.FieldTaskNo)
			}
			if _, exists := b.mutation.RequestNo(); exists {
				s.SetIgnore(dispatchtask.FieldRequestNo)
			}
			if _, exists := b.mutation.Target(); exists {
				s.SetIgnore(dispatchtask.FieldTarget)
			}
			if _, exists := b.mutation.TaskType(); exists {
				s.SetIgnore(dispatchtask.FieldTaskType)
			}
			if _, exists := b.mutation.Params(); exists {
				s.SetIgnore(dispatchtask.FieldParams)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DispatchTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DispatchTaskUpsertBulk) Ignore() *DispatchTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DispatchTaskUpsertBulk) DoNothing() *DispatchTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DispatchTaskCreateBulk.OnConflict
// documentation for more info.
func (u *DispatchTaskUpsertBulk) Update(set func(*DispatchTaskUpsert)) *DispatchTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DispatchTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DispatchTaskUpsertBulk) SetUpdatedAt(v time.Time) *DispatchTaskUpsertBulk {
	return u.Update(func(s *DispatchTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DispatchTaskUpsertBulk) UpdateUpdatedAt() *DispatchTaskUpsertBulk {
	return u.Update(func(s *DispatchTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *DispatchTaskUpsertBulk) SetStatus(v int64) *DispatchTaskUpsertBulk {
	return u.Update(func(s *DispatchTaskUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *DispatchTaskUpsertBulk) AddStatus(v int64) *DispatchTaskUpsertBulk {
	return u.Update(func(s *DispatchTaskUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DispatchTaskUpsertBulk) UpdateStatus() *DispatchTaskUpsertBulk {
	return u.Update(func(s *DispatchTaskUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *DispatchTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DispatchTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DispatchTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DispatchTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
