// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"oa.98ent.com/p9/node-dispatch/rpc/ent/node"
	"oa.98ent.com/p9/node-dispatch/rpc/ent/operatornode"
	"oa.98ent.com/p9/node-dispatch/rpc/ent/predicate"
)

// OperatorNodeQuery is the builder for querying OperatorNode entities.
type OperatorNodeQuery struct {
	config
	ctx        *QueryContext
	order      []operatornode.OrderOption
	inters     []Interceptor
	predicates []predicate.OperatorNode
	withNode   *NodeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OperatorNodeQuery builder.
func (_q *OperatorNodeQuery) Where(ps ...predicate.OperatorNode) *OperatorNodeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *OperatorNodeQuery) Limit(limit int) *OperatorNodeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *OperatorNodeQuery) Offset(offset int) *OperatorNodeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *OperatorNodeQuery) Unique(unique bool) *OperatorNodeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *OperatorNodeQuery) Order(o ...operatornode.OrderOption) *OperatorNodeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryNode chains the current query on the "node" edge.
func (_q *OperatorNodeQuery) QueryNode() *NodeQuery {
	query := (&NodeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(operatornode.Table, operatornode.FieldID, selector),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, operatornode.NodeTable, operatornode.NodeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OperatorNode entity from the query.
// Returns a *NotFoundError when no OperatorNode was found.
func (_q *OperatorNodeQuery) First(ctx context.Context) (*OperatorNode, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{operatornode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *OperatorNodeQuery) FirstX(ctx context.Context) *OperatorNode {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OperatorNode ID from the query.
// Returns a *NotFoundError when no OperatorNode ID was found.
func (_q *OperatorNodeQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{operatornode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *OperatorNodeQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OperatorNode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OperatorNode entity is found.
// Returns a *NotFoundError when no OperatorNode entities are found.
func (_q *OperatorNodeQuery) Only(ctx context.Context) (*OperatorNode, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{operatornode.Label}
	default:
		return nil, &NotSingularError{operatornode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *OperatorNodeQuery) OnlyX(ctx context.Context) *OperatorNode {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OperatorNode ID in the query.
// Returns a *NotSingularError when more than one OperatorNode ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *OperatorNodeQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{operatornode.Label}
	default:
		err = &NotSingularError{operatornode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *OperatorNodeQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OperatorNodes.
func (_q *OperatorNodeQuery) All(ctx context.Context) ([]*OperatorNode, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OperatorNode, *OperatorNodeQuery]()
	return withInterceptors[[]*OperatorNode](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *OperatorNodeQuery) AllX(ctx context.Context) []*OperatorNode {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OperatorNode IDs.
func (_q *OperatorNodeQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(operatornode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *OperatorNodeQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *OperatorNodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*OperatorNodeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *OperatorNodeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *OperatorNodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *OperatorNodeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OperatorNodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *OperatorNodeQuery) Clone() *OperatorNodeQuery {
	if _q == nil {
		return nil
	}
	return &OperatorNodeQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]operatornode.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.OperatorNode{}, _q.predicates...),
		withNode:   _q.withNode.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithNode tells the query-builder to eager-load the nodes that are connected to
// the "node" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OperatorNodeQuery) WithNode(opts ...func(*NodeQuery)) *OperatorNodeQuery {
	query := (&NodeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNode = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OperatorNode.Query().
//		GroupBy(operatornode.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *OperatorNodeQuery) GroupBy(field string, fields ...string) *OperatorNodeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OperatorNodeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = operatornode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.OperatorNode.Query().
//		Select(operatornode.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *OperatorNodeQuery) Select(fields ...string) *OperatorNodeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &OperatorNodeSelect{OperatorNodeQuery: _q}
	sbuild.label = operatornode.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OperatorNodeSelect configured with the given aggregations.
func (_q *OperatorNodeQuery) Aggregate(fns ...AggregateFunc) *OperatorNodeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *OperatorNodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !operatornode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *OperatorNodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OperatorNode, error) {
	var (
		nodes       = []*OperatorNode{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withNode != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OperatorNode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OperatorNode{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withNode; query != nil {
		if err := _q.loadNode(ctx, query, nodes, nil,
			func(n *OperatorNode, e *Node) { n.Edges.Node = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *OperatorNodeQuery) loadNode(ctx context.Context, query *NodeQuery, nodes []*OperatorNode, init func(*OperatorNode), assign func(*OperatorNode, *Node)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*OperatorNode)
	for i := range nodes {
		fk := nodes[i].NodeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(node.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "node_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *OperatorNodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *OperatorNodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(operatornode.Table, operatornode.Columns, sqlgraph.NewFieldSpec(operatornode.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, operatornode.FieldID)
		for i := range fields {
			if fields[i] != operatornode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withNode != nil {
			_spec.Node.AddColumnOnce(operatornode.FieldNodeID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *OperatorNodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(operatornode.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = operatornode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OperatorNodeGroupBy is the group-by builder for OperatorNode entities.
type OperatorNodeGroupBy struct {
	selector
	build *OperatorNodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *OperatorNodeGroupBy) Aggregate(fns ...AggregateFunc) *OperatorNodeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *OperatorNodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OperatorNodeQuery, *OperatorNodeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *OperatorNodeGroupBy) sqlScan(ctx context.Context, root *OperatorNodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OperatorNodeSelect is the builder for selecting fields of OperatorNode entities.
type OperatorNodeSelect struct {
	*OperatorNodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *OperatorNodeSelect) Aggregate(fns ...AggregateFunc) *OperatorNodeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *OperatorNodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OperatorNodeQuery, *OperatorNodeSelect](ctx, _s.OperatorNodeQuery, _s, _s.inters, v)
}

func (_s *OperatorNodeSelect) sqlScan(ctx context.Context, root *OperatorNodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
