// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_base.proto

package server

import (
	"context"

	"oa.98ent.com/p9/platform-base/rpc/internal/logic/pingservice"
	"oa.98ent.com/p9/platform-base/rpc/internal/svc"
	"oa.98ent.com/p9/platform-base/rpc/pb/platformbaserpc"
	"oa.98ent.com/p9/platform-base/rpc/pb/platformbaserpc/pingpb"
)

type PingServiceServer struct {
	svcCtx *svc.ServiceContext
	platformbaserpc.UnimplementedPingServiceServer
}

func NewPingServiceServer(svcCtx *svc.ServiceContext) *PingServiceServer {
	return &PingServiceServer{
		svcCtx: svcCtx,
	}
}

// Ping
func (s *PingServiceServer) Ping(ctx context.Context, in *pingpb.PingRequest) (*pingpb.PingResponse, error) {
	l := pingservicelogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
