// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_game.proto

package server

import (
	"context"

	"oa.98ent.com/p9/platform-game/rpc/internal/logic/pingservice"
	"oa.98ent.com/p9/platform-game/rpc/internal/svc"
	"oa.98ent.com/p9/platform-game/rpc/pb/platform_game"
)

type PingServiceServer struct {
	svcCtx *svc.ServiceContext
	platform_game.UnimplementedPingServiceServer
}

func NewPingServiceServer(svcCtx *svc.ServiceContext) *PingServiceServer {
	return &PingServiceServer{
		svcCtx: svcCtx,
	}
}

// 健康检查
func (s *PingServiceServer) Ping(ctx context.Context, in *platform_game.PingRequest) (*platform_game.PingResponse, error) {
	l := pingservicelogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
