syntax = "proto3";

package agentlineallocation;

option go_package = "oa.98ent.com/p9/platform-operator/rpc/pb/operator/agentlineallocation";

// 分站代理子线路分配信息
message AgentLineAllocationInfo {
  // 分配记录ID
  int64 id = 1;
  // 分站ID
  int64 operator_id = 2;
  // 代理子线路编码
  string agent_line_code = 3;
  // 分配时间, Unix毫秒时间戳
  int64 created_at = 4;
}

// 获取代理子线路分配列表请求
message ListAgentLineAllocationsRequest {
  // 分站ID
  int64 operator_id = 1;
}

// 获取代理子线路分配列表响应
message ListAgentLineAllocationsResponse {
  // 代理子线路分配列表
  repeated AgentLineAllocationInfo list = 1;
}

// 保存代理子线路分配请求
message SaveAgentLineAllocationsRequest {
  // 分站ID
  int64 operator_id = 1;
  // 当前分配的代理子线路编码
  repeated string agent_line_codes = 2;
}

// 保存代理子线路分配响应
message SaveAgentLineAllocationsResponse {}