// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_operator.proto

package server

import (
	"context"

	"oa.98ent.com/p9/platform-operator/rpc/internal/logic/agentlineallocationservice"
	"oa.98ent.com/p9/platform-operator/rpc/internal/svc"
	"oa.98ent.com/p9/platform-operator/rpc/pb/operator"
	"oa.98ent.com/p9/platform-operator/rpc/pb/operator/agentlineallocation"
)

type AgentLineAllocationServiceServer struct {
	svcCtx *svc.ServiceContext
	operator.UnimplementedAgentLineAllocationServiceServer
}

func NewAgentLineAllocationServiceServer(svcCtx *svc.ServiceContext) *AgentLineAllocationServiceServer {
	return &AgentLineAllocationServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取代理子线路分配列表
func (s *AgentLineAllocationServiceServer) List(ctx context.Context, in *agentlineallocation.ListAgentLineAllocationsRequest) (*agentlineallocation.ListAgentLineAllocationsResponse, error) {
	l := agentlineallocationservicelogic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

// 分配代理子线路
func (s *AgentLineAllocationServiceServer) Assign(ctx context.Context, in *agentlineallocation.AssignAgentLineRequest) (*agentlineallocation.AssignAgentLineResponse, error) {
	l := agentlineallocationservicelogic.NewAssignLogic(ctx, s.svcCtx)
	return l.Assign(in)
}

// 取消代理子线路分配
func (s *AgentLineAllocationServiceServer) Unassign(ctx context.Context, in *agentlineallocation.UnassignAgentLineRequest) (*agentlineallocation.UnassignAgentLineResponse, error) {
	l := agentlineallocationservicelogic.NewUnassignLogic(ctx, s.svcCtx)
	return l.Unassign(in)
}
