// Code generated by ent, DO NOT EDIT.

package gamecategory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"oa.98ent.com/p9/platform-game/rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLTE(FieldID, id))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldSourceID, v))
}

// CategoryCode applies equality check predicate on the "category_code" field. It's identical to CategoryCodeEQ.
func CategoryCode(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldCategoryCode, v))
}

// SourceCategoryCode applies equality check predicate on the "source_category_code" field. It's identical to SourceCategoryCodeEQ.
func SourceCategoryCode(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldSourceCategoryCode, v))
}

// SourceSortNo applies equality check predicate on the "source_sort_no" field. It's identical to SourceSortNoEQ.
func SourceSortNo(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldSourceSortNo, v))
}

// SortNo applies equality check predicate on the "sort_no" field. It's identical to SortNoEQ.
func SortNo(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldSortNo, v))
}

// SourceStatus applies equality check predicate on the "source_status" field. It's identical to SourceStatusEQ.
func SourceStatus(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldSourceStatus, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldStatus, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldUpdatedAt, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLTE(FieldSourceID, v))
}

// CategoryCodeEQ applies the EQ predicate on the "category_code" field.
func CategoryCodeEQ(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldCategoryCode, v))
}

// CategoryCodeNEQ applies the NEQ predicate on the "category_code" field.
func CategoryCodeNEQ(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNEQ(FieldCategoryCode, v))
}

// CategoryCodeIn applies the In predicate on the "category_code" field.
func CategoryCodeIn(vs ...string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldIn(FieldCategoryCode, vs...))
}

// CategoryCodeNotIn applies the NotIn predicate on the "category_code" field.
func CategoryCodeNotIn(vs ...string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNotIn(FieldCategoryCode, vs...))
}

// CategoryCodeGT applies the GT predicate on the "category_code" field.
func CategoryCodeGT(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGT(FieldCategoryCode, v))
}

// CategoryCodeGTE applies the GTE predicate on the "category_code" field.
func CategoryCodeGTE(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGTE(FieldCategoryCode, v))
}

// CategoryCodeLT applies the LT predicate on the "category_code" field.
func CategoryCodeLT(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLT(FieldCategoryCode, v))
}

// CategoryCodeLTE applies the LTE predicate on the "category_code" field.
func CategoryCodeLTE(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLTE(FieldCategoryCode, v))
}

// CategoryCodeContains applies the Contains predicate on the "category_code" field.
func CategoryCodeContains(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldContains(FieldCategoryCode, v))
}

// CategoryCodeHasPrefix applies the HasPrefix predicate on the "category_code" field.
func CategoryCodeHasPrefix(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldHasPrefix(FieldCategoryCode, v))
}

// CategoryCodeHasSuffix applies the HasSuffix predicate on the "category_code" field.
func CategoryCodeHasSuffix(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldHasSuffix(FieldCategoryCode, v))
}

// CategoryCodeEqualFold applies the EqualFold predicate on the "category_code" field.
func CategoryCodeEqualFold(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEqualFold(FieldCategoryCode, v))
}

// CategoryCodeContainsFold applies the ContainsFold predicate on the "category_code" field.
func CategoryCodeContainsFold(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldContainsFold(FieldCategoryCode, v))
}

// SourceCategoryCodeEQ applies the EQ predicate on the "source_category_code" field.
func SourceCategoryCodeEQ(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldSourceCategoryCode, v))
}

// SourceCategoryCodeNEQ applies the NEQ predicate on the "source_category_code" field.
func SourceCategoryCodeNEQ(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNEQ(FieldSourceCategoryCode, v))
}

// SourceCategoryCodeIn applies the In predicate on the "source_category_code" field.
func SourceCategoryCodeIn(vs ...string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldIn(FieldSourceCategoryCode, vs...))
}

// SourceCategoryCodeNotIn applies the NotIn predicate on the "source_category_code" field.
func SourceCategoryCodeNotIn(vs ...string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNotIn(FieldSourceCategoryCode, vs...))
}

// SourceCategoryCodeGT applies the GT predicate on the "source_category_code" field.
func SourceCategoryCodeGT(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGT(FieldSourceCategoryCode, v))
}

// SourceCategoryCodeGTE applies the GTE predicate on the "source_category_code" field.
func SourceCategoryCodeGTE(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGTE(FieldSourceCategoryCode, v))
}

// SourceCategoryCodeLT applies the LT predicate on the "source_category_code" field.
func SourceCategoryCodeLT(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLT(FieldSourceCategoryCode, v))
}

// SourceCategoryCodeLTE applies the LTE predicate on the "source_category_code" field.
func SourceCategoryCodeLTE(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLTE(FieldSourceCategoryCode, v))
}

// SourceCategoryCodeContains applies the Contains predicate on the "source_category_code" field.
func SourceCategoryCodeContains(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldContains(FieldSourceCategoryCode, v))
}

// SourceCategoryCodeHasPrefix applies the HasPrefix predicate on the "source_category_code" field.
func SourceCategoryCodeHasPrefix(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldHasPrefix(FieldSourceCategoryCode, v))
}

// SourceCategoryCodeHasSuffix applies the HasSuffix predicate on the "source_category_code" field.
func SourceCategoryCodeHasSuffix(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldHasSuffix(FieldSourceCategoryCode, v))
}

// SourceCategoryCodeEqualFold applies the EqualFold predicate on the "source_category_code" field.
func SourceCategoryCodeEqualFold(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEqualFold(FieldSourceCategoryCode, v))
}

// SourceCategoryCodeContainsFold applies the ContainsFold predicate on the "source_category_code" field.
func SourceCategoryCodeContainsFold(v string) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldContainsFold(FieldSourceCategoryCode, v))
}

// SourceSortNoEQ applies the EQ predicate on the "source_sort_no" field.
func SourceSortNoEQ(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldSourceSortNo, v))
}

// SourceSortNoNEQ applies the NEQ predicate on the "source_sort_no" field.
func SourceSortNoNEQ(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNEQ(FieldSourceSortNo, v))
}

// SourceSortNoIn applies the In predicate on the "source_sort_no" field.
func SourceSortNoIn(vs ...int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldIn(FieldSourceSortNo, vs...))
}

// SourceSortNoNotIn applies the NotIn predicate on the "source_sort_no" field.
func SourceSortNoNotIn(vs ...int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNotIn(FieldSourceSortNo, vs...))
}

// SourceSortNoGT applies the GT predicate on the "source_sort_no" field.
func SourceSortNoGT(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGT(FieldSourceSortNo, v))
}

// SourceSortNoGTE applies the GTE predicate on the "source_sort_no" field.
func SourceSortNoGTE(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGTE(FieldSourceSortNo, v))
}

// SourceSortNoLT applies the LT predicate on the "source_sort_no" field.
func SourceSortNoLT(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLT(FieldSourceSortNo, v))
}

// SourceSortNoLTE applies the LTE predicate on the "source_sort_no" field.
func SourceSortNoLTE(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLTE(FieldSourceSortNo, v))
}

// SourceSortNoIsNil applies the IsNil predicate on the "source_sort_no" field.
func SourceSortNoIsNil() predicate.GameCategory {
	return predicate.GameCategory(sql.FieldIsNull(FieldSourceSortNo))
}

// SourceSortNoNotNil applies the NotNil predicate on the "source_sort_no" field.
func SourceSortNoNotNil() predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNotNull(FieldSourceSortNo))
}

// SortNoEQ applies the EQ predicate on the "sort_no" field.
func SortNoEQ(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldSortNo, v))
}

// SortNoNEQ applies the NEQ predicate on the "sort_no" field.
func SortNoNEQ(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNEQ(FieldSortNo, v))
}

// SortNoIn applies the In predicate on the "sort_no" field.
func SortNoIn(vs ...int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldIn(FieldSortNo, vs...))
}

// SortNoNotIn applies the NotIn predicate on the "sort_no" field.
func SortNoNotIn(vs ...int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNotIn(FieldSortNo, vs...))
}

// SortNoGT applies the GT predicate on the "sort_no" field.
func SortNoGT(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGT(FieldSortNo, v))
}

// SortNoGTE applies the GTE predicate on the "sort_no" field.
func SortNoGTE(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGTE(FieldSortNo, v))
}

// SortNoLT applies the LT predicate on the "sort_no" field.
func SortNoLT(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLT(FieldSortNo, v))
}

// SortNoLTE applies the LTE predicate on the "sort_no" field.
func SortNoLTE(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLTE(FieldSortNo, v))
}

// SourceStatusEQ applies the EQ predicate on the "source_status" field.
func SourceStatusEQ(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldSourceStatus, v))
}

// SourceStatusNEQ applies the NEQ predicate on the "source_status" field.
func SourceStatusNEQ(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNEQ(FieldSourceStatus, v))
}

// SourceStatusIn applies the In predicate on the "source_status" field.
func SourceStatusIn(vs ...int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldIn(FieldSourceStatus, vs...))
}

// SourceStatusNotIn applies the NotIn predicate on the "source_status" field.
func SourceStatusNotIn(vs ...int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNotIn(FieldSourceStatus, vs...))
}

// SourceStatusGT applies the GT predicate on the "source_status" field.
func SourceStatusGT(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGT(FieldSourceStatus, v))
}

// SourceStatusGTE applies the GTE predicate on the "source_status" field.
func SourceStatusGTE(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGTE(FieldSourceStatus, v))
}

// SourceStatusLT applies the LT predicate on the "source_status" field.
func SourceStatusLT(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLT(FieldSourceStatus, v))
}

// SourceStatusLTE applies the LTE predicate on the "source_status" field.
func SourceStatusLTE(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLTE(FieldSourceStatus, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int64) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLTE(FieldStatus, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.GameCategory {
	return predicate.GameCategory(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GameCategory {
	return predicate.GameCategory(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GameCategory) predicate.GameCategory {
	return predicate.GameCategory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GameCategory) predicate.GameCategory {
	return predicate.GameCategory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GameCategory) predicate.GameCategory {
	return predicate.GameCategory(sql.NotPredicates(p))
}
