// Code generated by ent, DO NOT EDIT.

package promotion

import (
	"oa.98ent.com/p9/core/example/promo-api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldUpdatedAt, v))
}

// OperatorCode applies equality check predicate on the "operator_code" field. It's identical to OperatorCodeEQ.
func OperatorCode(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldOperatorCode, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldTitle, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldUpdatedAt, v))
}

// OperatorCodeEQ applies the EQ predicate on the "operator_code" field.
func OperatorCodeEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldOperatorCode, v))
}

// OperatorCodeNEQ applies the NEQ predicate on the "operator_code" field.
func OperatorCodeNEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldOperatorCode, v))
}

// OperatorCodeIn applies the In predicate on the "operator_code" field.
func OperatorCodeIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldOperatorCode, vs...))
}

// OperatorCodeNotIn applies the NotIn predicate on the "operator_code" field.
func OperatorCodeNotIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldOperatorCode, vs...))
}

// OperatorCodeGT applies the GT predicate on the "operator_code" field.
func OperatorCodeGT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldOperatorCode, v))
}

// OperatorCodeGTE applies the GTE predicate on the "operator_code" field.
func OperatorCodeGTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldOperatorCode, v))
}

// OperatorCodeLT applies the LT predicate on the "operator_code" field.
func OperatorCodeLT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldOperatorCode, v))
}

// OperatorCodeLTE applies the LTE predicate on the "operator_code" field.
func OperatorCodeLTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldOperatorCode, v))
}

// OperatorCodeContains applies the Contains predicate on the "operator_code" field.
func OperatorCodeContains(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContains(FieldOperatorCode, v))
}

// OperatorCodeHasPrefix applies the HasPrefix predicate on the "operator_code" field.
func OperatorCodeHasPrefix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasPrefix(FieldOperatorCode, v))
}

// OperatorCodeHasSuffix applies the HasSuffix predicate on the "operator_code" field.
func OperatorCodeHasSuffix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasSuffix(FieldOperatorCode, v))
}

// OperatorCodeIsNil applies the IsNil predicate on the "operator_code" field.
func OperatorCodeIsNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldIsNull(FieldOperatorCode))
}

// OperatorCodeNotNil applies the NotNil predicate on the "operator_code" field.
func OperatorCodeNotNil() predicate.Promotion {
	return predicate.Promotion(sql.FieldNotNull(FieldOperatorCode))
}

// OperatorCodeEqualFold applies the EqualFold predicate on the "operator_code" field.
func OperatorCodeEqualFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEqualFold(FieldOperatorCode, v))
}

// OperatorCodeContainsFold applies the ContainsFold predicate on the "operator_code" field.
func OperatorCodeContainsFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContainsFold(FieldOperatorCode, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Promotion {
	return predicate.Promotion(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Promotion {
	return predicate.Promotion(sql.FieldContainsFold(FieldTitle, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Promotion) predicate.Promotion {
	return predicate.Promotion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Promotion) predicate.Promotion {
	return predicate.Promotion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Promotion) predicate.Promotion {
	return predicate.Promotion(sql.NotPredicates(p))
}
