// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_base.proto

package regionservice

import (
	"context"

	"oa.98ent.com/p9/platform-base/rpc/pb/platformbaserpc"

	"oa.98ent.com/p9/platform-base/rpc/pb/platformbaserpc/regionpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RegionService interface {
		// 修改国家地区
		Update(ctx context.Context, in *regionpb.UpdateRegionRequest, opts ...grpc.CallOption) (*regionpb.UpdateRegionResponse, error)
		// 获取国家地区
		Get(ctx context.Context, in *regionpb.GetRegionRequest, opts ...grpc.CallOption) (*regionpb.GetRegionResponse, error)
		// 按编码获取国家地区
		GetByCode(ctx context.Context, in *regionpb.GetRegionByCodeRequest, opts ...grpc.CallOption) (*regionpb.GetRegionByCodeResponse, error)
		// 获取国家地区管理列表
		List(ctx context.Context, in *regionpb.ListRegionsRequest, opts ...grpc.CallOption) (*regionpb.ListRegionsResponse, error)
		// 获取全部国家地区
		ListAll(ctx context.Context, in *regionpb.ListAllRegionsRequest, opts ...grpc.CallOption) (*regionpb.ListAllRegionsResponse, error)
		// 调整国家地区排序
		Reorder(ctx context.Context, in *regionpb.ReorderRegionRequest, opts ...grpc.CallOption) (*regionpb.ReorderRegionResponse, error)
	}

	defaultRegionService struct {
		cli zrpc.Client
	}
)

func NewRegionService(cli zrpc.Client) RegionService {
	return &defaultRegionService{
		cli: cli,
	}
}

// 修改国家地区
func (m *defaultRegionService) Update(ctx context.Context, in *regionpb.UpdateRegionRequest, opts ...grpc.CallOption) (*regionpb.UpdateRegionResponse, error) {
	client := platformbaserpc.NewRegionServiceClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}

// 获取国家地区
func (m *defaultRegionService) Get(ctx context.Context, in *regionpb.GetRegionRequest, opts ...grpc.CallOption) (*regionpb.GetRegionResponse, error) {
	client := platformbaserpc.NewRegionServiceClient(m.cli.Conn())
	return client.Get(ctx, in, opts...)
}

// 按编码获取国家地区
func (m *defaultRegionService) GetByCode(ctx context.Context, in *regionpb.GetRegionByCodeRequest, opts ...grpc.CallOption) (*regionpb.GetRegionByCodeResponse, error) {
	client := platformbaserpc.NewRegionServiceClient(m.cli.Conn())
	return client.GetByCode(ctx, in, opts...)
}

// 获取国家地区管理列表
func (m *defaultRegionService) List(ctx context.Context, in *regionpb.ListRegionsRequest, opts ...grpc.CallOption) (*regionpb.ListRegionsResponse, error) {
	client := platformbaserpc.NewRegionServiceClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

// 获取全部国家地区
func (m *defaultRegionService) ListAll(ctx context.Context, in *regionpb.ListAllRegionsRequest, opts ...grpc.CallOption) (*regionpb.ListAllRegionsResponse, error) {
	client := platformbaserpc.NewRegionServiceClient(m.cli.Conn())
	return client.ListAll(ctx, in, opts...)
}

// 调整国家地区排序
func (m *defaultRegionService) Reorder(ctx context.Context, in *regionpb.ReorderRegionRequest, opts ...grpc.CallOption) (*regionpb.ReorderRegionResponse, error) {
	client := platformbaserpc.NewRegionServiceClient(m.cli.Conn())
	return client.Reorder(ctx, in, opts...)
}
