// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.1
// source: types/language_allocation.proto

package languageallocation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分站语言分配信息
type LanguageAllocationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分配记录ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分站ID
	OperatorId int64 `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	// 语言编码
	LanguageCode string `protobuf:"bytes,3,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	// 分配时间, Unix毫秒时间戳
	CreatedAt     int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguageAllocationInfo) Reset() {
	*x = LanguageAllocationInfo{}
	mi := &file_types_language_allocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageAllocationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageAllocationInfo) ProtoMessage() {}

func (x *LanguageAllocationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_allocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageAllocationInfo.ProtoReflect.Descriptor instead.
func (*LanguageAllocationInfo) Descriptor() ([]byte, []int) {
	return file_types_language_allocation_proto_rawDescGZIP(), []int{0}
}

func (x *LanguageAllocationInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LanguageAllocationInfo) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *LanguageAllocationInfo) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *LanguageAllocationInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 获取语言分配列表请求
type ListLanguageAllocationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码, 从1开始
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// 每页数量
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 分站ID
	OperatorId *int64 `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"`
	// 语言编码
	LanguageCode  *string `protobuf:"bytes,4,opt,name=language_code,json=languageCode,proto3,oneof" json:"language_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLanguageAllocationsRequest) Reset() {
	*x = ListLanguageAllocationsRequest{}
	mi := &file_types_language_allocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLanguageAllocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLanguageAllocationsRequest) ProtoMessage() {}

func (x *ListLanguageAllocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_allocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLanguageAllocationsRequest.ProtoReflect.Descriptor instead.
func (*ListLanguageAllocationsRequest) Descriptor() ([]byte, []int) {
	return file_types_language_allocation_proto_rawDescGZIP(), []int{1}
}

func (x *ListLanguageAllocationsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLanguageAllocationsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLanguageAllocationsRequest) GetOperatorId() int64 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

func (x *ListLanguageAllocationsRequest) GetLanguageCode() string {
	if x != nil && x.LanguageCode != nil {
		return *x.LanguageCode
	}
	return ""
}

// 获取语言分配列表响应
type ListLanguageAllocationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 数据总数
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 语言分配列表
	List          []*LanguageAllocationInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLanguageAllocationsResponse) Reset() {
	*x = ListLanguageAllocationsResponse{}
	mi := &file_types_language_allocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLanguageAllocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLanguageAllocationsResponse) ProtoMessage() {}

func (x *ListLanguageAllocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_allocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLanguageAllocationsResponse.ProtoReflect.Descriptor instead.
func (*ListLanguageAllocationsResponse) Descriptor() ([]byte, []int) {
	return file_types_language_allocation_proto_rawDescGZIP(), []int{2}
}

func (x *ListLanguageAllocationsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListLanguageAllocationsResponse) GetList() []*LanguageAllocationInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 分配语言请求
type AssignLanguageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	OperatorId int64 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	// 语言编码
	LanguageCode  string `protobuf:"bytes,2,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignLanguageRequest) Reset() {
	*x = AssignLanguageRequest{}
	mi := &file_types_language_allocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignLanguageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignLanguageRequest) ProtoMessage() {}

func (x *AssignLanguageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_allocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignLanguageRequest.ProtoReflect.Descriptor instead.
func (*AssignLanguageRequest) Descriptor() ([]byte, []int) {
	return file_types_language_allocation_proto_rawDescGZIP(), []int{3}
}

func (x *AssignLanguageRequest) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *AssignLanguageRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

// 分配语言响应
type AssignLanguageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分配记录ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignLanguageResponse) Reset() {
	*x = AssignLanguageResponse{}
	mi := &file_types_language_allocation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignLanguageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignLanguageResponse) ProtoMessage() {}

func (x *AssignLanguageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_allocation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignLanguageResponse.ProtoReflect.Descriptor instead.
func (*AssignLanguageResponse) Descriptor() ([]byte, []int) {
	return file_types_language_allocation_proto_rawDescGZIP(), []int{4}
}

func (x *AssignLanguageResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 取消语言分配请求
type UnassignLanguageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	OperatorId int64 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	// 语言编码
	LanguageCode  string `protobuf:"bytes,2,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignLanguageRequest) Reset() {
	*x = UnassignLanguageRequest{}
	mi := &file_types_language_allocation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignLanguageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignLanguageRequest) ProtoMessage() {}

func (x *UnassignLanguageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_allocation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignLanguageRequest.ProtoReflect.Descriptor instead.
func (*UnassignLanguageRequest) Descriptor() ([]byte, []int) {
	return file_types_language_allocation_proto_rawDescGZIP(), []int{5}
}

func (x *UnassignLanguageRequest) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *UnassignLanguageRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

// 取消语言分配响应
type UnassignLanguageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignLanguageResponse) Reset() {
	*x = UnassignLanguageResponse{}
	mi := &file_types_language_allocation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignLanguageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignLanguageResponse) ProtoMessage() {}

func (x *UnassignLanguageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_language_allocation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignLanguageResponse.ProtoReflect.Descriptor instead.
func (*UnassignLanguageResponse) Descriptor() ([]byte, []int) {
	return file_types_language_allocation_proto_rawDescGZIP(), []int{6}
}

var File_types_language_allocation_proto protoreflect.FileDescriptor

const file_types_language_allocation_proto_rawDesc = "" +
	"\n" +
	"\x1ftypes/language_allocation.proto\x12\x12languageallocation\"\x8d\x01\n" +
	"\x16LanguageAllocationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12#\n" +
	"\rlanguage_code\x18\x03 \x01(\tR\flanguageCode\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\xc3\x01\n" +
	"\x1eListLanguageAllocationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12$\n" +
	"\voperator_id\x18\x03 \x01(\x03H\x00R\n" +
	"operatorId\x88\x01\x01\x12(\n" +
	"\rlanguage_code\x18\x04 \x01(\tH\x01R\flanguageCode\x88\x01\x01B\x0e\n" +
	"\f_operator_idB\x10\n" +
	"\x0e_language_code\"w\n" +
	"\x1fListLanguageAllocationsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12>\n" +
	"\x04list\x18\x02 \x03(\v2*.languageallocation.LanguageAllocationInfoR\x04list\"]\n" +
	"\x15AssignLanguageRequest\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x03R\n" +
	"operatorId\x12#\n" +
	"\rlanguage_code\x18\x02 \x01(\tR\flanguageCode\"(\n" +
	"\x16AssignLanguageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"_\n" +
	"\x17UnassignLanguageRequest\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x03R\n" +
	"operatorId\x12#\n" +
	"\rlanguage_code\x18\x02 \x01(\tR\flanguageCode\"\x1a\n" +
	"\x18UnassignLanguageResponseBFZDoa.98ent.com/p9/platform-operator/rpc/pb/operator/languageallocationb\x06proto3"

var (
	file_types_language_allocation_proto_rawDescOnce sync.Once
	file_types_language_allocation_proto_rawDescData []byte
)

func file_types_language_allocation_proto_rawDescGZIP() []byte {
	file_types_language_allocation_proto_rawDescOnce.Do(func() {
		file_types_language_allocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_language_allocation_proto_rawDesc), len(file_types_language_allocation_proto_rawDesc)))
	})
	return file_types_language_allocation_proto_rawDescData
}

var file_types_language_allocation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_types_language_allocation_proto_goTypes = []any{
	(*LanguageAllocationInfo)(nil),          // 0: languageallocation.LanguageAllocationInfo
	(*ListLanguageAllocationsRequest)(nil),  // 1: languageallocation.ListLanguageAllocationsRequest
	(*ListLanguageAllocationsResponse)(nil), // 2: languageallocation.ListLanguageAllocationsResponse
	(*AssignLanguageRequest)(nil),           // 3: languageallocation.AssignLanguageRequest
	(*AssignLanguageResponse)(nil),          // 4: languageallocation.AssignLanguageResponse
	(*UnassignLanguageRequest)(nil),         // 5: languageallocation.UnassignLanguageRequest
	(*UnassignLanguageResponse)(nil),        // 6: languageallocation.UnassignLanguageResponse
}
var file_types_language_allocation_proto_depIdxs = []int32{
	0, // 0: languageallocation.ListLanguageAllocationsResponse.list:type_name -> languageallocation.LanguageAllocationInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_types_language_allocation_proto_init() }
func file_types_language_allocation_proto_init() {
	if File_types_language_allocation_proto != nil {
		return
	}
	file_types_language_allocation_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_language_allocation_proto_rawDesc), len(file_types_language_allocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_language_allocation_proto_goTypes,
		DependencyIndexes: file_types_language_allocation_proto_depIdxs,
		MessageInfos:      file_types_language_allocation_proto_msgTypes,
	}.Build()
	File_types_language_allocation_proto = out.File
	file_types_language_allocation_proto_goTypes = nil
	file_types_language_allocation_proto_depIdxs = nil
}
