// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.1
// source: types/platform_operator_admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分站管理员信息
type AdminInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 管理员ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分站ID
	OperatorId int64 `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	// 分站名称
	OperatorName string `protobuf:"bytes,3,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`
	// 账号
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	// 显示名称
	DisplayName string `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// 状态: 1启用, 2停用
	Status int64 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	// 创建时间, Unix毫秒时间戳
	CreatedAt int64 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新时间, Unix毫秒时间戳
	UpdatedAt     int64 `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminInfo) Reset() {
	*x = AdminInfo{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminInfo) ProtoMessage() {}

func (x *AdminInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminInfo.ProtoReflect.Descriptor instead.
func (*AdminInfo) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminInfo) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *AdminInfo) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *AdminInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AdminInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AdminInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 创建分站管理员请求
type CreateAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	OperatorId int64 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	// 账号
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// 密码
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// 显示名称
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// 状态: 1启用, 2停用
	Status        *int64 `protobuf:"varint,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminRequest) Reset() {
	*x = CreateAdminRequest{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminRequest) ProtoMessage() {}

func (x *CreateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminRequest.ProtoReflect.Descriptor instead.
func (*CreateAdminRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAdminRequest) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *CreateAdminRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAdminRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAdminRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateAdminRequest) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// 创建分站管理员响应
type CreateAdminResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 管理员ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminResponse) Reset() {
	*x = CreateAdminResponse{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminResponse) ProtoMessage() {}

func (x *CreateAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminResponse.ProtoReflect.Descriptor instead.
func (*CreateAdminResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAdminResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取分站管理员列表请求
type ListAdminsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码, 从1开始
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// 每页数量
	PageSize int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 分站ID
	OperatorId *int64 `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"`
	// 搜索关键字, 匹配账号或显示名称
	Keyword *string `protobuf:"bytes,4,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"`
	// 状态: 1启用, 2停用
	Status        *int64 `protobuf:"varint,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminsRequest) Reset() {
	*x = ListAdminsRequest{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminsRequest) ProtoMessage() {}

func (x *ListAdminsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminsRequest.ProtoReflect.Descriptor instead.
func (*ListAdminsRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListAdminsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAdminsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAdminsRequest) GetOperatorId() int64 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

func (x *ListAdminsRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *ListAdminsRequest) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// 获取分站管理员列表响应
type ListAdminsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 数据总数
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 管理员列表
	List          []*AdminInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminsResponse) Reset() {
	*x = ListAdminsResponse{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminsResponse) ProtoMessage() {}

func (x *ListAdminsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminsResponse.ProtoReflect.Descriptor instead.
func (*ListAdminsResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListAdminsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAdminsResponse) GetList() []*AdminInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 重置分站管理员密码请求
type ResetAdminPasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 管理员ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 新密码
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAdminPasswordRequest) Reset() {
	*x = ResetAdminPasswordRequest{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAdminPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAdminPasswordRequest) ProtoMessage() {}

func (x *ResetAdminPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAdminPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetAdminPasswordRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ResetAdminPasswordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResetAdminPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 重置分站管理员密码响应
type ResetAdminPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAdminPasswordResponse) Reset() {
	*x = ResetAdminPasswordResponse{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAdminPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAdminPasswordResponse) ProtoMessage() {}

func (x *ResetAdminPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAdminPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetAdminPasswordResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{6}
}

// 更新分站管理员请求
type UpdateAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 管理员ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 账号
	Username *string `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	// 显示名称
	DisplayName *string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	// 状态: 1启用, 2停用
	Status *int64 `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	// 密码
	Password      *string `protobuf:"bytes,5,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminRequest) Reset() {
	*x = UpdateAdminRequest{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminRequest) ProtoMessage() {}

func (x *UpdateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdminRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAdminRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAdminRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateAdminRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateAdminRequest) GetStatus() int64 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *UpdateAdminRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

// 更新分站管理员响应
type UpdateAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminResponse) Reset() {
	*x = UpdateAdminResponse{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminResponse) ProtoMessage() {}

func (x *UpdateAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminResponse.ProtoReflect.Descriptor instead.
func (*UpdateAdminResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{8}
}

// 更新分站管理员状态请求
type UpdateAdminStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 管理员ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 状态: 1启用, 2停用
	Status        int64 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminStatusRequest) Reset() {
	*x = UpdateAdminStatusRequest{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminStatusRequest) ProtoMessage() {}

func (x *UpdateAdminStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdminStatusRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAdminStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAdminStatusRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 更新分站管理员状态响应
type UpdateAdminStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminStatusResponse) Reset() {
	*x = UpdateAdminStatusResponse{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminStatusResponse) ProtoMessage() {}

func (x *UpdateAdminStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateAdminStatusResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{10}
}

// 按分站删除管理员请求
type DeleteAdminsByOperatorIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	OperatorId    int64 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminsByOperatorIdRequest) Reset() {
	*x = DeleteAdminsByOperatorIdRequest{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminsByOperatorIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminsByOperatorIdRequest) ProtoMessage() {}

func (x *DeleteAdminsByOperatorIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminsByOperatorIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdminsByOperatorIdRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAdminsByOperatorIdRequest) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

// 按分站删除管理员响应
type DeleteAdminsByOperatorIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminsByOperatorIdResponse) Reset() {
	*x = DeleteAdminsByOperatorIdResponse{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminsByOperatorIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminsByOperatorIdResponse) ProtoMessage() {}

func (x *DeleteAdminsByOperatorIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminsByOperatorIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteAdminsByOperatorIdResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{12}
}

// 检测分站管理员是否已存在请求
type ExistsAdminByOperatorIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站ID
	OperatorId    int64 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsAdminByOperatorIdRequest) Reset() {
	*x = ExistsAdminByOperatorIdRequest{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsAdminByOperatorIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsAdminByOperatorIdRequest) ProtoMessage() {}

func (x *ExistsAdminByOperatorIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsAdminByOperatorIdRequest.ProtoReflect.Descriptor instead.
func (*ExistsAdminByOperatorIdRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{13}
}

func (x *ExistsAdminByOperatorIdRequest) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

// 检测分站管理员是否已存在响应
type ExistsAdminByOperatorIdResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否已存在管理员
	Exists        bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsAdminByOperatorIdResponse) Reset() {
	*x = ExistsAdminByOperatorIdResponse{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsAdminByOperatorIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsAdminByOperatorIdResponse) ProtoMessage() {}

func (x *ExistsAdminByOperatorIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsAdminByOperatorIdResponse.ProtoReflect.Descriptor instead.
func (*ExistsAdminByOperatorIdResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{14}
}

func (x *ExistsAdminByOperatorIdResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// 获取分站管理员请求
type GetAdminRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 表自增ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminRequest) Reset() {
	*x = GetAdminRequest{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminRequest) ProtoMessage() {}

func (x *GetAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminRequest.ProtoReflect.Descriptor instead.
func (*GetAdminRequest) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{15}
}

func (x *GetAdminRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取分站管理员响应
type GetAdminResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分站管理员信息
	Admin         *AdminInfo `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminResponse) Reset() {
	*x = GetAdminResponse{}
	mi := &file_types_platform_operator_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminResponse) ProtoMessage() {}

func (x *GetAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_platform_operator_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminResponse.ProtoReflect.Descriptor instead.
func (*GetAdminResponse) Descriptor() ([]byte, []int) {
	return file_types_platform_operator_admin_proto_rawDescGZIP(), []int{16}
}

func (x *GetAdminResponse) GetAdmin() *AdminInfo {
	if x != nil {
		return x.Admin
	}
	return nil
}

var File_types_platform_operator_admin_proto protoreflect.FileDescriptor

const file_types_platform_operator_admin_proto_rawDesc = "" +
	"\n" +
	"#types/platform_operator_admin.proto\x12\x17platform_operator_admin\"\xf6\x01\n" +
	"\tAdminInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12#\n" +
	"\roperator_name\x18\x03 \x01(\tR\foperatorName\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xb8\x01\n" +
	"\x12CreateAdminRequest\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x03R\n" +
	"operatorId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\x03H\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"%\n" +
	"\x13CreateAdminResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xcd\x01\n" +
	"\x11ListAdminsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12$\n" +
	"\voperator_id\x18\x03 \x01(\x03H\x00R\n" +
	"operatorId\x88\x01\x01\x12\x1d\n" +
	"\akeyword\x18\x04 \x01(\tH\x01R\akeyword\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\x03H\x02R\x06status\x88\x01\x01B\x0e\n" +
	"\f_operator_idB\n" +
	"\n" +
	"\b_keywordB\t\n" +
	"\a_status\"b\n" +
	"\x12ListAdminsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x126\n" +
	"\x04list\x18\x02 \x03(\v2\".platform_operator_admin.AdminInfoR\x04list\"G\n" +
	"\x19ResetAdminPasswordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x1c\n" +
	"\x1aResetAdminPasswordResponse\"\xe1\x01\n" +
	"\x12UpdateAdminRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\x03 \x01(\tH\x01R\vdisplayName\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\x03H\x02R\x06status\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x05 \x01(\tH\x03R\bpassword\x88\x01\x01B\v\n" +
	"\t_usernameB\x0f\n" +
	"\r_display_nameB\t\n" +
	"\a_statusB\v\n" +
	"\t_password\"\x15\n" +
	"\x13UpdateAdminResponse\"B\n" +
	"\x18UpdateAdminStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\"\x1b\n" +
	"\x19UpdateAdminStatusResponse\"B\n" +
	"\x1fDeleteAdminsByOperatorIdRequest\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x03R\n" +
	"operatorId\"\"\n" +
	" DeleteAdminsByOperatorIdResponse\"A\n" +
	"\x1eExistsAdminByOperatorIdRequest\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x03R\n" +
	"operatorId\"9\n" +
	"\x1fExistsAdminByOperatorIdResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"!\n" +
	"\x0fGetAdminRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"L\n" +
	"\x10GetAdminResponse\x128\n" +
	"\x05admin\x18\x01 \x01(\v2\".platform_operator_admin.AdminInfoR\x05adminBFZDoa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/adminpbb\x06proto3"

var (
	file_types_platform_operator_admin_proto_rawDescOnce sync.Once
	file_types_platform_operator_admin_proto_rawDescData []byte
)

func file_types_platform_operator_admin_proto_rawDescGZIP() []byte {
	file_types_platform_operator_admin_proto_rawDescOnce.Do(func() {
		file_types_platform_operator_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_platform_operator_admin_proto_rawDesc), len(file_types_platform_operator_admin_proto_rawDesc)))
	})
	return file_types_platform_operator_admin_proto_rawDescData
}

var file_types_platform_operator_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_types_platform_operator_admin_proto_goTypes = []any{
	(*AdminInfo)(nil),                        // 0: platform_operator_admin.AdminInfo
	(*CreateAdminRequest)(nil),               // 1: platform_operator_admin.CreateAdminRequest
	(*CreateAdminResponse)(nil),              // 2: platform_operator_admin.CreateAdminResponse
	(*ListAdminsRequest)(nil),                // 3: platform_operator_admin.ListAdminsRequest
	(*ListAdminsResponse)(nil),               // 4: platform_operator_admin.ListAdminsResponse
	(*ResetAdminPasswordRequest)(nil),        // 5: platform_operator_admin.ResetAdminPasswordRequest
	(*ResetAdminPasswordResponse)(nil),       // 6: platform_operator_admin.ResetAdminPasswordResponse
	(*UpdateAdminRequest)(nil),               // 7: platform_operator_admin.UpdateAdminRequest
	(*UpdateAdminResponse)(nil),              // 8: platform_operator_admin.UpdateAdminResponse
	(*UpdateAdminStatusRequest)(nil),         // 9: platform_operator_admin.UpdateAdminStatusRequest
	(*UpdateAdminStatusResponse)(nil),        // 10: platform_operator_admin.UpdateAdminStatusResponse
	(*DeleteAdminsByOperatorIdRequest)(nil),  // 11: platform_operator_admin.DeleteAdminsByOperatorIdRequest
	(*DeleteAdminsByOperatorIdResponse)(nil), // 12: platform_operator_admin.DeleteAdminsByOperatorIdResponse
	(*ExistsAdminByOperatorIdRequest)(nil),   // 13: platform_operator_admin.ExistsAdminByOperatorIdRequest
	(*ExistsAdminByOperatorIdResponse)(nil),  // 14: platform_operator_admin.ExistsAdminByOperatorIdResponse
	(*GetAdminRequest)(nil),                  // 15: platform_operator_admin.GetAdminRequest
	(*GetAdminResponse)(nil),                 // 16: platform_operator_admin.GetAdminResponse
}
var file_types_platform_operator_admin_proto_depIdxs = []int32{
	0, // 0: platform_operator_admin.ListAdminsResponse.list:type_name -> platform_operator_admin.AdminInfo
	0, // 1: platform_operator_admin.GetAdminResponse.admin:type_name -> platform_operator_admin.AdminInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_platform_operator_admin_proto_init() }
func file_types_platform_operator_admin_proto_init() {
	if File_types_platform_operator_admin_proto != nil {
		return
	}
	file_types_platform_operator_admin_proto_msgTypes[1].OneofWrappers = []any{}
	file_types_platform_operator_admin_proto_msgTypes[3].OneofWrappers = []any{}
	file_types_platform_operator_admin_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_platform_operator_admin_proto_rawDesc), len(file_types_platform_operator_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_platform_operator_admin_proto_goTypes,
		DependencyIndexes: file_types_platform_operator_admin_proto_depIdxs,
		MessageInfos:      file_types_platform_operator_admin_proto_msgTypes,
	}.Build()
	File_types_platform_operator_admin_proto = out.File
	file_types_platform_operator_admin_proto_goTypes = nil
	file_types_platform_operator_admin_proto_depIdxs = nil
}
