syntax = "proto3";

package operator_base_operator;

option go_package = "oa.98ent.com/p9/operator-base/rpc/pb/operatorbaserpc/operatorpb";

// operator 初始化基础信息
message OperatorInitializationInfo {
  // operator 全局唯一业务编码
  string code = 1;
  // operator 名称
  string name = 2;
  // IANA 时区编码
  string timezone_code = 3;
  // 结算货币编码
  string settlement_currency_code = 4;
  // operator 状态: 1正常, 2暂停, 3关闭
  int64 status = 5;
}

// operator 初始化域名信息
message OperatorDomainInitializationInfo {
  // 域名, 不包含协议和端口
  string domain_name = 1;
  // 域名类型: 1分站后台, 2代理后台, 3会员H5
  int64 domain_type = 2;
}

// 初始化 operator 请求
message InitializeOperatorRequest {
  // operator 基础信息
  OperatorInitializationInfo operator = 1;
  // 当前有效域名
  repeated OperatorDomainInitializationInfo domains = 2;
  // 当前有效语言编码
  repeated string language_codes = 3;
  // 当前有效经营地区编码
  repeated string region_codes = 4;
  // 当前有效代理子线路编码
  repeated string agent_line_codes = 5;
}

// 初始化 operator 响应
message InitializeOperatorResponse {}