FROM golang:1.26-alpine AS builder

# Define the project name | 定义项目名称
ARG PROJECT=platform-game
# Define the author | 定义作者
ARG AUTHOR="Zoelly1210@proton.me"

LABEL org.opencontainers.image.authors=${AUTHOR}

WORKDIR /app
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

# 复制源代码
COPY . .

# 编译 RPC
# RUN go build -trimpath -o platform_game_rpc ./rpc/platform_game.go

# 最终镜像
FROM alpine:3.22

ARG CONFIG_FILE=platform_game.yaml
ARG AUTHOR="Zoelly1210@proton.me"

LABEL org.opencontainers.image.authors=${AUTHOR}

WORKDIR /app
ENV TZ=Asia/Shanghai
RUN apk update --no-cache && apk add --no-cache tzdata

# 从 builder 阶段复制编译好的二进制
COPY --from=builder /app/platform_game_rpc ./
COPY ./rpc/etc/${CONFIG_FILE} ./etc/

EXPOSE 19003

ENTRYPOINT ["./platform_game_rpc", "-f", "etc/platform_game.yaml"]
