// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: platform_game.proto

package server

import (
	"context"

	"oa.98ent.com/p9/platform-game/rpc/internal/logic/operatorgameservice"
	"oa.98ent.com/p9/platform-game/rpc/internal/svc"
	"oa.98ent.com/p9/platform-game/rpc/pb/platform_game"
)

type OperatorGameServiceServer struct {
	svcCtx *svc.ServiceContext
	platform_game.UnimplementedOperatorGameServiceServer
}

func NewOperatorGameServiceServer(svcCtx *svc.ServiceContext) *OperatorGameServiceServer {
	return &OperatorGameServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取分站游戏列表
func (s *OperatorGameServiceServer) GetOperatorGameList(ctx context.Context, in *platform_game.GetOperatorGameListRequest) (*platform_game.GetOperatorGameListResp, error) {
	l := operatorgameservicelogic.NewGetOperatorGameListLogic(ctx, s.svcCtx)
	return l.GetOperatorGameList(in)
}

// 批量修改分站游戏状态
func (s *OperatorGameServiceServer) BatchUpdateOperatorGameStatus(ctx context.Context, in *platform_game.BatchUpdateOperatorGameStatusRequest) (*platform_game.BatchUpdateOperatorGameStatusResp, error) {
	l := operatorgameservicelogic.NewBatchUpdateOperatorGameStatusLogic(ctx, s.svcCtx)
	return l.BatchUpdateOperatorGameStatus(in)
}

// 保存分站游戏分配
func (s *OperatorGameServiceServer) SaveOperatorGameAllocation(ctx context.Context, in *platform_game.SaveOperatorGameAllocationRequest) (*platform_game.SaveOperatorGameAllocationResp, error) {
	l := operatorgameservicelogic.NewSaveOperatorGameAllocationLogic(ctx, s.svcCtx)
	return l.SaveOperatorGameAllocation(in)
}
