// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.0
// source: platform_operator.proto

package platformoperatorrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	agentlineallocationpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/agentlineallocationpb"
	basicresourceallocationpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/basicresourceallocationpb"
	domainpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/domainpb"
	languageallocationpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/languageallocationpb"
	operatorpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/operatorpb"
	pingpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/pingpb"
	profilepb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/profilepb"
	regionallocationpb "oa.98ent.com/p9/platform-operator/rpc/pb/platformoperatorrpc/regionallocationpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PingService_Ping_FullMethodName = "/platform_operator.PingService/Ping"
)

// PingServiceClient is the client API for PingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Ping 服务
type PingServiceClient interface {
	// Ping
	Ping(ctx context.Context, in *pingpb.PingRequest, opts ...grpc.CallOption) (*pingpb.PingResponse, error)
}

type pingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPingServiceClient(cc grpc.ClientConnInterface) PingServiceClient {
	return &pingServiceClient{cc}
}

func (c *pingServiceClient) Ping(ctx context.Context, in *pingpb.PingRequest, opts ...grpc.CallOption) (*pingpb.PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pingpb.PingResponse)
	err := c.cc.Invoke(ctx, PingService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingServiceServer is the server API for PingService service.
// All implementations must embed UnimplementedPingServiceServer
// for forward compatibility.
//
// Ping 服务
type PingServiceServer interface {
	// Ping
	Ping(context.Context, *pingpb.PingRequest) (*pingpb.PingResponse, error)
	mustEmbedUnimplementedPingServiceServer()
}

// UnimplementedPingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPingServiceServer struct{}

func (UnimplementedPingServiceServer) Ping(context.Context, *pingpb.PingRequest) (*pingpb.PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPingServiceServer) mustEmbedUnimplementedPingServiceServer() {}
func (UnimplementedPingServiceServer) testEmbeddedByValue()                     {}

// UnsafePingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingServiceServer will
// result in compilation errors.
type UnsafePingServiceServer interface {
	mustEmbedUnimplementedPingServiceServer()
}

func RegisterPingServiceServer(s grpc.ServiceRegistrar, srv PingServiceServer) {
	// If the following call panics, it indicates UnimplementedPingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PingService_ServiceDesc, srv)
}

func _PingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pingpb.PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PingService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServiceServer).Ping(ctx, req.(*pingpb.PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PingService_ServiceDesc is the grpc.ServiceDesc for PingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_operator.PingService",
	HandlerType: (*PingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PingService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform_operator.proto",
}

const (
	OperatorService_Create_FullMethodName   = "/platform_operator.OperatorService/Create"
	OperatorService_Update_FullMethodName   = "/platform_operator.OperatorService/Update"
	OperatorService_Get_FullMethodName      = "/platform_operator.OperatorService/Get"
	OperatorService_List_FullMethodName     = "/platform_operator.OperatorService/List"
	OperatorService_Complete_FullMethodName = "/platform_operator.OperatorService/Complete"
	OperatorService_Publish_FullMethodName  = "/platform_operator.OperatorService/Publish"
)

// OperatorServiceClient is the client API for OperatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 分站服务
type OperatorServiceClient interface {
	// 创建分站
	Create(ctx context.Context, in *operatorpb.CreateOperatorRequest, opts ...grpc.CallOption) (*operatorpb.CreateOperatorResponse, error)
	// 修改分站
	Update(ctx context.Context, in *operatorpb.UpdateOperatorRequest, opts ...grpc.CallOption) (*operatorpb.UpdateOperatorResponse, error)
	// 获取分站
	Get(ctx context.Context, in *operatorpb.GetOperatorRequest, opts ...grpc.CallOption) (*operatorpb.GetOperatorResponse, error)
	// 获取分站管理列表
	List(ctx context.Context, in *operatorpb.ListOperatorsRequest, opts ...grpc.CallOption) (*operatorpb.ListOperatorsResponse, error)
	// 完成分站创建
	Complete(ctx context.Context, in *operatorpb.CompleteOperatorRequest, opts ...grpc.CallOption) (*operatorpb.CompleteOperatorResponse, error)
	// 发布分站
	Publish(ctx context.Context, in *operatorpb.PublishOperatorRequest, opts ...grpc.CallOption) (*operatorpb.PublishOperatorResponse, error)
}

type operatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatorServiceClient(cc grpc.ClientConnInterface) OperatorServiceClient {
	return &operatorServiceClient{cc}
}

func (c *operatorServiceClient) Create(ctx context.Context, in *operatorpb.CreateOperatorRequest, opts ...grpc.CallOption) (*operatorpb.CreateOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operatorpb.CreateOperatorResponse)
	err := c.cc.Invoke(ctx, OperatorService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) Update(ctx context.Context, in *operatorpb.UpdateOperatorRequest, opts ...grpc.CallOption) (*operatorpb.UpdateOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operatorpb.UpdateOperatorResponse)
	err := c.cc.Invoke(ctx, OperatorService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) Get(ctx context.Context, in *operatorpb.GetOperatorRequest, opts ...grpc.CallOption) (*operatorpb.GetOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operatorpb.GetOperatorResponse)
	err := c.cc.Invoke(ctx, OperatorService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) List(ctx context.Context, in *operatorpb.ListOperatorsRequest, opts ...grpc.CallOption) (*operatorpb.ListOperatorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operatorpb.ListOperatorsResponse)
	err := c.cc.Invoke(ctx, OperatorService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) Complete(ctx context.Context, in *operatorpb.CompleteOperatorRequest, opts ...grpc.CallOption) (*operatorpb.CompleteOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operatorpb.CompleteOperatorResponse)
	err := c.cc.Invoke(ctx, OperatorService_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) Publish(ctx context.Context, in *operatorpb.PublishOperatorRequest, opts ...grpc.CallOption) (*operatorpb.PublishOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operatorpb.PublishOperatorResponse)
	err := c.cc.Invoke(ctx, OperatorService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperatorServiceServer is the server API for OperatorService service.
// All implementations must embed UnimplementedOperatorServiceServer
// for forward compatibility.
//
// 分站服务
type OperatorServiceServer interface {
	// 创建分站
	Create(context.Context, *operatorpb.CreateOperatorRequest) (*operatorpb.CreateOperatorResponse, error)
	// 修改分站
	Update(context.Context, *operatorpb.UpdateOperatorRequest) (*operatorpb.UpdateOperatorResponse, error)
	// 获取分站
	Get(context.Context, *operatorpb.GetOperatorRequest) (*operatorpb.GetOperatorResponse, error)
	// 获取分站管理列表
	List(context.Context, *operatorpb.ListOperatorsRequest) (*operatorpb.ListOperatorsResponse, error)
	// 完成分站创建
	Complete(context.Context, *operatorpb.CompleteOperatorRequest) (*operatorpb.CompleteOperatorResponse, error)
	// 发布分站
	Publish(context.Context, *operatorpb.PublishOperatorRequest) (*operatorpb.PublishOperatorResponse, error)
	mustEmbedUnimplementedOperatorServiceServer()
}

// UnimplementedOperatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperatorServiceServer struct{}

func (UnimplementedOperatorServiceServer) Create(context.Context, *operatorpb.CreateOperatorRequest) (*operatorpb.CreateOperatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedOperatorServiceServer) Update(context.Context, *operatorpb.UpdateOperatorRequest) (*operatorpb.UpdateOperatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedOperatorServiceServer) Get(context.Context, *operatorpb.GetOperatorRequest) (*operatorpb.GetOperatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedOperatorServiceServer) List(context.Context, *operatorpb.ListOperatorsRequest) (*operatorpb.ListOperatorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedOperatorServiceServer) Complete(context.Context, *operatorpb.CompleteOperatorRequest) (*operatorpb.CompleteOperatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedOperatorServiceServer) Publish(context.Context, *operatorpb.PublishOperatorRequest) (*operatorpb.PublishOperatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedOperatorServiceServer) mustEmbedUnimplementedOperatorServiceServer() {}
func (UnimplementedOperatorServiceServer) testEmbeddedByValue()                         {}

// UnsafeOperatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperatorServiceServer will
// result in compilation errors.
type UnsafeOperatorServiceServer interface {
	mustEmbedUnimplementedOperatorServiceServer()
}

func RegisterOperatorServiceServer(s grpc.ServiceRegistrar, srv OperatorServiceServer) {
	// If the following call panics, it indicates UnimplementedOperatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperatorService_ServiceDesc, srv)
}

func _OperatorService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(operatorpb.CreateOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).Create(ctx, req.(*operatorpb.CreateOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(operatorpb.UpdateOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).Update(ctx, req.(*operatorpb.UpdateOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(operatorpb.GetOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).Get(ctx, req.(*operatorpb.GetOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(operatorpb.ListOperatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).List(ctx, req.(*operatorpb.ListOperatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(operatorpb.CompleteOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).Complete(ctx, req.(*operatorpb.CompleteOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(operatorpb.PublishOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).Publish(ctx, req.(*operatorpb.PublishOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperatorService_ServiceDesc is the grpc.ServiceDesc for OperatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_operator.OperatorService",
	HandlerType: (*OperatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _OperatorService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _OperatorService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _OperatorService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _OperatorService_List_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _OperatorService_Complete_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _OperatorService_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform_operator.proto",
}

const (
	OperatorProfileService_Create_FullMethodName = "/platform_operator.OperatorProfileService/Create"
	OperatorProfileService_Update_FullMethodName = "/platform_operator.OperatorProfileService/Update"
	OperatorProfileService_Get_FullMethodName    = "/platform_operator.OperatorProfileService/Get"
)

// OperatorProfileServiceClient is the client API for OperatorProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 分站档案服务
type OperatorProfileServiceClient interface {
	// 创建分站档案
	Create(ctx context.Context, in *profilepb.CreateOperatorProfileRequest, opts ...grpc.CallOption) (*profilepb.CreateOperatorProfileResponse, error)
	// 修改分站档案
	Update(ctx context.Context, in *profilepb.UpdateOperatorProfileRequest, opts ...grpc.CallOption) (*profilepb.UpdateOperatorProfileResponse, error)
	// 获取分站档案
	Get(ctx context.Context, in *profilepb.GetOperatorProfileRequest, opts ...grpc.CallOption) (*profilepb.GetOperatorProfileResponse, error)
}

type operatorProfileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatorProfileServiceClient(cc grpc.ClientConnInterface) OperatorProfileServiceClient {
	return &operatorProfileServiceClient{cc}
}

func (c *operatorProfileServiceClient) Create(ctx context.Context, in *profilepb.CreateOperatorProfileRequest, opts ...grpc.CallOption) (*profilepb.CreateOperatorProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(profilepb.CreateOperatorProfileResponse)
	err := c.cc.Invoke(ctx, OperatorProfileService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorProfileServiceClient) Update(ctx context.Context, in *profilepb.UpdateOperatorProfileRequest, opts ...grpc.CallOption) (*profilepb.UpdateOperatorProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(profilepb.UpdateOperatorProfileResponse)
	err := c.cc.Invoke(ctx, OperatorProfileService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorProfileServiceClient) Get(ctx context.Context, in *profilepb.GetOperatorProfileRequest, opts ...grpc.CallOption) (*profilepb.GetOperatorProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(profilepb.GetOperatorProfileResponse)
	err := c.cc.Invoke(ctx, OperatorProfileService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperatorProfileServiceServer is the server API for OperatorProfileService service.
// All implementations must embed UnimplementedOperatorProfileServiceServer
// for forward compatibility.
//
// 分站档案服务
type OperatorProfileServiceServer interface {
	// 创建分站档案
	Create(context.Context, *profilepb.CreateOperatorProfileRequest) (*profilepb.CreateOperatorProfileResponse, error)
	// 修改分站档案
	Update(context.Context, *profilepb.UpdateOperatorProfileRequest) (*profilepb.UpdateOperatorProfileResponse, error)
	// 获取分站档案
	Get(context.Context, *profilepb.GetOperatorProfileRequest) (*profilepb.GetOperatorProfileResponse, error)
	mustEmbedUnimplementedOperatorProfileServiceServer()
}

// UnimplementedOperatorProfileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperatorProfileServiceServer struct{}

func (UnimplementedOperatorProfileServiceServer) Create(context.Context, *profilepb.CreateOperatorProfileRequest) (*profilepb.CreateOperatorProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedOperatorProfileServiceServer) Update(context.Context, *profilepb.UpdateOperatorProfileRequest) (*profilepb.UpdateOperatorProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedOperatorProfileServiceServer) Get(context.Context, *profilepb.GetOperatorProfileRequest) (*profilepb.GetOperatorProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedOperatorProfileServiceServer) mustEmbedUnimplementedOperatorProfileServiceServer() {
}
func (UnimplementedOperatorProfileServiceServer) testEmbeddedByValue() {}

// UnsafeOperatorProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperatorProfileServiceServer will
// result in compilation errors.
type UnsafeOperatorProfileServiceServer interface {
	mustEmbedUnimplementedOperatorProfileServiceServer()
}

func RegisterOperatorProfileServiceServer(s grpc.ServiceRegistrar, srv OperatorProfileServiceServer) {
	// If the following call panics, it indicates UnimplementedOperatorProfileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperatorProfileService_ServiceDesc, srv)
}

func _OperatorProfileService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(profilepb.CreateOperatorProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorProfileServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorProfileService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorProfileServiceServer).Create(ctx, req.(*profilepb.CreateOperatorProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorProfileService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(profilepb.UpdateOperatorProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorProfileServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorProfileService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorProfileServiceServer).Update(ctx, req.(*profilepb.UpdateOperatorProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorProfileService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(profilepb.GetOperatorProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorProfileServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorProfileService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorProfileServiceServer).Get(ctx, req.(*profilepb.GetOperatorProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperatorProfileService_ServiceDesc is the grpc.ServiceDesc for OperatorProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperatorProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_operator.OperatorProfileService",
	HandlerType: (*OperatorProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _OperatorProfileService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _OperatorProfileService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _OperatorProfileService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform_operator.proto",
}

const (
	OperatorDomainService_Create_FullMethodName = "/platform_operator.OperatorDomainService/Create"
	OperatorDomainService_Update_FullMethodName = "/platform_operator.OperatorDomainService/Update"
	OperatorDomainService_Get_FullMethodName    = "/platform_operator.OperatorDomainService/Get"
	OperatorDomainService_List_FullMethodName   = "/platform_operator.OperatorDomainService/List"
	OperatorDomainService_Delete_FullMethodName = "/platform_operator.OperatorDomainService/Delete"
)

// OperatorDomainServiceClient is the client API for OperatorDomainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 分站域名服务
type OperatorDomainServiceClient interface {
	// 创建分站域名
	Create(ctx context.Context, in *domainpb.CreateDomainRequest, opts ...grpc.CallOption) (*domainpb.CreateDomainResponse, error)
	// 修改分站域名
	Update(ctx context.Context, in *domainpb.UpdateDomainRequest, opts ...grpc.CallOption) (*domainpb.UpdateDomainResponse, error)
	// 获取分站域名
	Get(ctx context.Context, in *domainpb.GetDomainRequest, opts ...grpc.CallOption) (*domainpb.GetDomainResponse, error)
	// 获取分站域名管理列表
	List(ctx context.Context, in *domainpb.ListDomainsRequest, opts ...grpc.CallOption) (*domainpb.ListDomainsResponse, error)
	// 删除分站域名
	Delete(ctx context.Context, in *domainpb.DeleteDomainRequest, opts ...grpc.CallOption) (*domainpb.DeleteDomainResponse, error)
}

type operatorDomainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatorDomainServiceClient(cc grpc.ClientConnInterface) OperatorDomainServiceClient {
	return &operatorDomainServiceClient{cc}
}

func (c *operatorDomainServiceClient) Create(ctx context.Context, in *domainpb.CreateDomainRequest, opts ...grpc.CallOption) (*domainpb.CreateDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(domainpb.CreateDomainResponse)
	err := c.cc.Invoke(ctx, OperatorDomainService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorDomainServiceClient) Update(ctx context.Context, in *domainpb.UpdateDomainRequest, opts ...grpc.CallOption) (*domainpb.UpdateDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(domainpb.UpdateDomainResponse)
	err := c.cc.Invoke(ctx, OperatorDomainService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorDomainServiceClient) Get(ctx context.Context, in *domainpb.GetDomainRequest, opts ...grpc.CallOption) (*domainpb.GetDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(domainpb.GetDomainResponse)
	err := c.cc.Invoke(ctx, OperatorDomainService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorDomainServiceClient) List(ctx context.Context, in *domainpb.ListDomainsRequest, opts ...grpc.CallOption) (*domainpb.ListDomainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(domainpb.ListDomainsResponse)
	err := c.cc.Invoke(ctx, OperatorDomainService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorDomainServiceClient) Delete(ctx context.Context, in *domainpb.DeleteDomainRequest, opts ...grpc.CallOption) (*domainpb.DeleteDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(domainpb.DeleteDomainResponse)
	err := c.cc.Invoke(ctx, OperatorDomainService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperatorDomainServiceServer is the server API for OperatorDomainService service.
// All implementations must embed UnimplementedOperatorDomainServiceServer
// for forward compatibility.
//
// 分站域名服务
type OperatorDomainServiceServer interface {
	// 创建分站域名
	Create(context.Context, *domainpb.CreateDomainRequest) (*domainpb.CreateDomainResponse, error)
	// 修改分站域名
	Update(context.Context, *domainpb.UpdateDomainRequest) (*domainpb.UpdateDomainResponse, error)
	// 获取分站域名
	Get(context.Context, *domainpb.GetDomainRequest) (*domainpb.GetDomainResponse, error)
	// 获取分站域名管理列表
	List(context.Context, *domainpb.ListDomainsRequest) (*domainpb.ListDomainsResponse, error)
	// 删除分站域名
	Delete(context.Context, *domainpb.DeleteDomainRequest) (*domainpb.DeleteDomainResponse, error)
	mustEmbedUnimplementedOperatorDomainServiceServer()
}

// UnimplementedOperatorDomainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperatorDomainServiceServer struct{}

func (UnimplementedOperatorDomainServiceServer) Create(context.Context, *domainpb.CreateDomainRequest) (*domainpb.CreateDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedOperatorDomainServiceServer) Update(context.Context, *domainpb.UpdateDomainRequest) (*domainpb.UpdateDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedOperatorDomainServiceServer) Get(context.Context, *domainpb.GetDomainRequest) (*domainpb.GetDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedOperatorDomainServiceServer) List(context.Context, *domainpb.ListDomainsRequest) (*domainpb.ListDomainsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedOperatorDomainServiceServer) Delete(context.Context, *domainpb.DeleteDomainRequest) (*domainpb.DeleteDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedOperatorDomainServiceServer) mustEmbedUnimplementedOperatorDomainServiceServer() {}
func (UnimplementedOperatorDomainServiceServer) testEmbeddedByValue()                               {}

// UnsafeOperatorDomainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperatorDomainServiceServer will
// result in compilation errors.
type UnsafeOperatorDomainServiceServer interface {
	mustEmbedUnimplementedOperatorDomainServiceServer()
}

func RegisterOperatorDomainServiceServer(s grpc.ServiceRegistrar, srv OperatorDomainServiceServer) {
	// If the following call panics, it indicates UnimplementedOperatorDomainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperatorDomainService_ServiceDesc, srv)
}

func _OperatorDomainService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domainpb.CreateDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorDomainServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorDomainService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorDomainServiceServer).Create(ctx, req.(*domainpb.CreateDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorDomainService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domainpb.UpdateDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorDomainServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorDomainService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorDomainServiceServer).Update(ctx, req.(*domainpb.UpdateDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorDomainService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domainpb.GetDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorDomainServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorDomainService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorDomainServiceServer).Get(ctx, req.(*domainpb.GetDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorDomainService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domainpb.ListDomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorDomainServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorDomainService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorDomainServiceServer).List(ctx, req.(*domainpb.ListDomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorDomainService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domainpb.DeleteDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorDomainServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorDomainService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorDomainServiceServer).Delete(ctx, req.(*domainpb.DeleteDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperatorDomainService_ServiceDesc is the grpc.ServiceDesc for OperatorDomainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperatorDomainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_operator.OperatorDomainService",
	HandlerType: (*OperatorDomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _OperatorDomainService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _OperatorDomainService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _OperatorDomainService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _OperatorDomainService_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _OperatorDomainService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform_operator.proto",
}

const (
	BasicResourceAllocationService_List_FullMethodName = "/platform_operator.BasicResourceAllocationService/List"
)

// BasicResourceAllocationServiceClient is the client API for BasicResourceAllocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 分站基础资源分配服务
type BasicResourceAllocationServiceClient interface {
	// 获取基础资源分配列表
	List(ctx context.Context, in *basicresourceallocationpb.ListBasicResourceAllocationsRequest, opts ...grpc.CallOption) (*basicresourceallocationpb.ListBasicResourceAllocationsResponse, error)
}

type basicResourceAllocationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBasicResourceAllocationServiceClient(cc grpc.ClientConnInterface) BasicResourceAllocationServiceClient {
	return &basicResourceAllocationServiceClient{cc}
}

func (c *basicResourceAllocationServiceClient) List(ctx context.Context, in *basicresourceallocationpb.ListBasicResourceAllocationsRequest, opts ...grpc.CallOption) (*basicresourceallocationpb.ListBasicResourceAllocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(basicresourceallocationpb.ListBasicResourceAllocationsResponse)
	err := c.cc.Invoke(ctx, BasicResourceAllocationService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BasicResourceAllocationServiceServer is the server API for BasicResourceAllocationService service.
// All implementations must embed UnimplementedBasicResourceAllocationServiceServer
// for forward compatibility.
//
// 分站基础资源分配服务
type BasicResourceAllocationServiceServer interface {
	// 获取基础资源分配列表
	List(context.Context, *basicresourceallocationpb.ListBasicResourceAllocationsRequest) (*basicresourceallocationpb.ListBasicResourceAllocationsResponse, error)
	mustEmbedUnimplementedBasicResourceAllocationServiceServer()
}

// UnimplementedBasicResourceAllocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBasicResourceAllocationServiceServer struct{}

func (UnimplementedBasicResourceAllocationServiceServer) List(context.Context, *basicresourceallocationpb.ListBasicResourceAllocationsRequest) (*basicresourceallocationpb.ListBasicResourceAllocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedBasicResourceAllocationServiceServer) mustEmbedUnimplementedBasicResourceAllocationServiceServer() {
}
func (UnimplementedBasicResourceAllocationServiceServer) testEmbeddedByValue() {}

// UnsafeBasicResourceAllocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BasicResourceAllocationServiceServer will
// result in compilation errors.
type UnsafeBasicResourceAllocationServiceServer interface {
	mustEmbedUnimplementedBasicResourceAllocationServiceServer()
}

func RegisterBasicResourceAllocationServiceServer(s grpc.ServiceRegistrar, srv BasicResourceAllocationServiceServer) {
	// If the following call panics, it indicates UnimplementedBasicResourceAllocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BasicResourceAllocationService_ServiceDesc, srv)
}

func _BasicResourceAllocationService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(basicresourceallocationpb.ListBasicResourceAllocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasicResourceAllocationServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasicResourceAllocationService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasicResourceAllocationServiceServer).List(ctx, req.(*basicresourceallocationpb.ListBasicResourceAllocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BasicResourceAllocationService_ServiceDesc is the grpc.ServiceDesc for BasicResourceAllocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BasicResourceAllocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_operator.BasicResourceAllocationService",
	HandlerType: (*BasicResourceAllocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _BasicResourceAllocationService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform_operator.proto",
}

const (
	LanguageAllocationService_List_FullMethodName = "/platform_operator.LanguageAllocationService/List"
	LanguageAllocationService_Save_FullMethodName = "/platform_operator.LanguageAllocationService/Save"
)

// LanguageAllocationServiceClient is the client API for LanguageAllocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 分站语言分配服务
type LanguageAllocationServiceClient interface {
	// 获取语言分配列表
	List(ctx context.Context, in *languageallocationpb.ListLanguageAllocationsRequest, opts ...grpc.CallOption) (*languageallocationpb.ListLanguageAllocationsResponse, error)
	// 保存语言分配
	Save(ctx context.Context, in *languageallocationpb.SaveLanguageAllocationsRequest, opts ...grpc.CallOption) (*languageallocationpb.SaveLanguageAllocationsResponse, error)
}

type languageAllocationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLanguageAllocationServiceClient(cc grpc.ClientConnInterface) LanguageAllocationServiceClient {
	return &languageAllocationServiceClient{cc}
}

func (c *languageAllocationServiceClient) List(ctx context.Context, in *languageallocationpb.ListLanguageAllocationsRequest, opts ...grpc.CallOption) (*languageallocationpb.ListLanguageAllocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(languageallocationpb.ListLanguageAllocationsResponse)
	err := c.cc.Invoke(ctx, LanguageAllocationService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *languageAllocationServiceClient) Save(ctx context.Context, in *languageallocationpb.SaveLanguageAllocationsRequest, opts ...grpc.CallOption) (*languageallocationpb.SaveLanguageAllocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(languageallocationpb.SaveLanguageAllocationsResponse)
	err := c.cc.Invoke(ctx, LanguageAllocationService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LanguageAllocationServiceServer is the server API for LanguageAllocationService service.
// All implementations must embed UnimplementedLanguageAllocationServiceServer
// for forward compatibility.
//
// 分站语言分配服务
type LanguageAllocationServiceServer interface {
	// 获取语言分配列表
	List(context.Context, *languageallocationpb.ListLanguageAllocationsRequest) (*languageallocationpb.ListLanguageAllocationsResponse, error)
	// 保存语言分配
	Save(context.Context, *languageallocationpb.SaveLanguageAllocationsRequest) (*languageallocationpb.SaveLanguageAllocationsResponse, error)
	mustEmbedUnimplementedLanguageAllocationServiceServer()
}

// UnimplementedLanguageAllocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLanguageAllocationServiceServer struct{}

func (UnimplementedLanguageAllocationServiceServer) List(context.Context, *languageallocationpb.ListLanguageAllocationsRequest) (*languageallocationpb.ListLanguageAllocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedLanguageAllocationServiceServer) Save(context.Context, *languageallocationpb.SaveLanguageAllocationsRequest) (*languageallocationpb.SaveLanguageAllocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedLanguageAllocationServiceServer) mustEmbedUnimplementedLanguageAllocationServiceServer() {
}
func (UnimplementedLanguageAllocationServiceServer) testEmbeddedByValue() {}

// UnsafeLanguageAllocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LanguageAllocationServiceServer will
// result in compilation errors.
type UnsafeLanguageAllocationServiceServer interface {
	mustEmbedUnimplementedLanguageAllocationServiceServer()
}

func RegisterLanguageAllocationServiceServer(s grpc.ServiceRegistrar, srv LanguageAllocationServiceServer) {
	// If the following call panics, it indicates UnimplementedLanguageAllocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LanguageAllocationService_ServiceDesc, srv)
}

func _LanguageAllocationService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(languageallocationpb.ListLanguageAllocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanguageAllocationServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanguageAllocationService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanguageAllocationServiceServer).List(ctx, req.(*languageallocationpb.ListLanguageAllocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanguageAllocationService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(languageallocationpb.SaveLanguageAllocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanguageAllocationServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanguageAllocationService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanguageAllocationServiceServer).Save(ctx, req.(*languageallocationpb.SaveLanguageAllocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LanguageAllocationService_ServiceDesc is the grpc.ServiceDesc for LanguageAllocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LanguageAllocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_operator.LanguageAllocationService",
	HandlerType: (*LanguageAllocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _LanguageAllocationService_List_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _LanguageAllocationService_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform_operator.proto",
}

const (
	RegionAllocationService_List_FullMethodName = "/platform_operator.RegionAllocationService/List"
	RegionAllocationService_Save_FullMethodName = "/platform_operator.RegionAllocationService/Save"
)

// RegionAllocationServiceClient is the client API for RegionAllocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 分站经营地区分配服务
type RegionAllocationServiceClient interface {
	// 获取经营地区分配列表
	List(ctx context.Context, in *regionallocationpb.ListRegionAllocationsRequest, opts ...grpc.CallOption) (*regionallocationpb.ListRegionAllocationsResponse, error)
	// 保存经营地区分配
	Save(ctx context.Context, in *regionallocationpb.SaveRegionAllocationsRequest, opts ...grpc.CallOption) (*regionallocationpb.SaveRegionAllocationsResponse, error)
}

type regionAllocationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegionAllocationServiceClient(cc grpc.ClientConnInterface) RegionAllocationServiceClient {
	return &regionAllocationServiceClient{cc}
}

func (c *regionAllocationServiceClient) List(ctx context.Context, in *regionallocationpb.ListRegionAllocationsRequest, opts ...grpc.CallOption) (*regionallocationpb.ListRegionAllocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(regionallocationpb.ListRegionAllocationsResponse)
	err := c.cc.Invoke(ctx, RegionAllocationService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionAllocationServiceClient) Save(ctx context.Context, in *regionallocationpb.SaveRegionAllocationsRequest, opts ...grpc.CallOption) (*regionallocationpb.SaveRegionAllocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(regionallocationpb.SaveRegionAllocationsResponse)
	err := c.cc.Invoke(ctx, RegionAllocationService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegionAllocationServiceServer is the server API for RegionAllocationService service.
// All implementations must embed UnimplementedRegionAllocationServiceServer
// for forward compatibility.
//
// 分站经营地区分配服务
type RegionAllocationServiceServer interface {
	// 获取经营地区分配列表
	List(context.Context, *regionallocationpb.ListRegionAllocationsRequest) (*regionallocationpb.ListRegionAllocationsResponse, error)
	// 保存经营地区分配
	Save(context.Context, *regionallocationpb.SaveRegionAllocationsRequest) (*regionallocationpb.SaveRegionAllocationsResponse, error)
	mustEmbedUnimplementedRegionAllocationServiceServer()
}

// UnimplementedRegionAllocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegionAllocationServiceServer struct{}

func (UnimplementedRegionAllocationServiceServer) List(context.Context, *regionallocationpb.ListRegionAllocationsRequest) (*regionallocationpb.ListRegionAllocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRegionAllocationServiceServer) Save(context.Context, *regionallocationpb.SaveRegionAllocationsRequest) (*regionallocationpb.SaveRegionAllocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedRegionAllocationServiceServer) mustEmbedUnimplementedRegionAllocationServiceServer() {
}
func (UnimplementedRegionAllocationServiceServer) testEmbeddedByValue() {}

// UnsafeRegionAllocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegionAllocationServiceServer will
// result in compilation errors.
type UnsafeRegionAllocationServiceServer interface {
	mustEmbedUnimplementedRegionAllocationServiceServer()
}

func RegisterRegionAllocationServiceServer(s grpc.ServiceRegistrar, srv RegionAllocationServiceServer) {
	// If the following call panics, it indicates UnimplementedRegionAllocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegionAllocationService_ServiceDesc, srv)
}

func _RegionAllocationService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(regionallocationpb.ListRegionAllocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionAllocationServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionAllocationService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionAllocationServiceServer).List(ctx, req.(*regionallocationpb.ListRegionAllocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionAllocationService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(regionallocationpb.SaveRegionAllocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionAllocationServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegionAllocationService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionAllocationServiceServer).Save(ctx, req.(*regionallocationpb.SaveRegionAllocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegionAllocationService_ServiceDesc is the grpc.ServiceDesc for RegionAllocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegionAllocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_operator.RegionAllocationService",
	HandlerType: (*RegionAllocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _RegionAllocationService_List_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _RegionAllocationService_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform_operator.proto",
}

const (
	AgentLineAllocationService_List_FullMethodName = "/platform_operator.AgentLineAllocationService/List"
	AgentLineAllocationService_Save_FullMethodName = "/platform_operator.AgentLineAllocationService/Save"
)

// AgentLineAllocationServiceClient is the client API for AgentLineAllocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 分站代理子线路分配服务
type AgentLineAllocationServiceClient interface {
	// 获取代理子线路分配列表
	List(ctx context.Context, in *agentlineallocationpb.ListAgentLineAllocationsRequest, opts ...grpc.CallOption) (*agentlineallocationpb.ListAgentLineAllocationsResponse, error)
	// 保存代理子线路分配
	Save(ctx context.Context, in *agentlineallocationpb.SaveAgentLineAllocationsRequest, opts ...grpc.CallOption) (*agentlineallocationpb.SaveAgentLineAllocationsResponse, error)
}

type agentLineAllocationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentLineAllocationServiceClient(cc grpc.ClientConnInterface) AgentLineAllocationServiceClient {
	return &agentLineAllocationServiceClient{cc}
}

func (c *agentLineAllocationServiceClient) List(ctx context.Context, in *agentlineallocationpb.ListAgentLineAllocationsRequest, opts ...grpc.CallOption) (*agentlineallocationpb.ListAgentLineAllocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(agentlineallocationpb.ListAgentLineAllocationsResponse)
	err := c.cc.Invoke(ctx, AgentLineAllocationService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentLineAllocationServiceClient) Save(ctx context.Context, in *agentlineallocationpb.SaveAgentLineAllocationsRequest, opts ...grpc.CallOption) (*agentlineallocationpb.SaveAgentLineAllocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(agentlineallocationpb.SaveAgentLineAllocationsResponse)
	err := c.cc.Invoke(ctx, AgentLineAllocationService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentLineAllocationServiceServer is the server API for AgentLineAllocationService service.
// All implementations must embed UnimplementedAgentLineAllocationServiceServer
// for forward compatibility.
//
// 分站代理子线路分配服务
type AgentLineAllocationServiceServer interface {
	// 获取代理子线路分配列表
	List(context.Context, *agentlineallocationpb.ListAgentLineAllocationsRequest) (*agentlineallocationpb.ListAgentLineAllocationsResponse, error)
	// 保存代理子线路分配
	Save(context.Context, *agentlineallocationpb.SaveAgentLineAllocationsRequest) (*agentlineallocationpb.SaveAgentLineAllocationsResponse, error)
	mustEmbedUnimplementedAgentLineAllocationServiceServer()
}

// UnimplementedAgentLineAllocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentLineAllocationServiceServer struct{}

func (UnimplementedAgentLineAllocationServiceServer) List(context.Context, *agentlineallocationpb.ListAgentLineAllocationsRequest) (*agentlineallocationpb.ListAgentLineAllocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAgentLineAllocationServiceServer) Save(context.Context, *agentlineallocationpb.SaveAgentLineAllocationsRequest) (*agentlineallocationpb.SaveAgentLineAllocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedAgentLineAllocationServiceServer) mustEmbedUnimplementedAgentLineAllocationServiceServer() {
}
func (UnimplementedAgentLineAllocationServiceServer) testEmbeddedByValue() {}

// UnsafeAgentLineAllocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentLineAllocationServiceServer will
// result in compilation errors.
type UnsafeAgentLineAllocationServiceServer interface {
	mustEmbedUnimplementedAgentLineAllocationServiceServer()
}

func RegisterAgentLineAllocationServiceServer(s grpc.ServiceRegistrar, srv AgentLineAllocationServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentLineAllocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentLineAllocationService_ServiceDesc, srv)
}

func _AgentLineAllocationService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(agentlineallocationpb.ListAgentLineAllocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentLineAllocationServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentLineAllocationService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentLineAllocationServiceServer).List(ctx, req.(*agentlineallocationpb.ListAgentLineAllocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentLineAllocationService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(agentlineallocationpb.SaveAgentLineAllocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentLineAllocationServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentLineAllocationService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentLineAllocationServiceServer).Save(ctx, req.(*agentlineallocationpb.SaveAgentLineAllocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentLineAllocationService_ServiceDesc is the grpc.ServiceDesc for AgentLineAllocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentLineAllocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform_operator.AgentLineAllocationService",
	HandlerType: (*AgentLineAllocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AgentLineAllocationService_List_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _AgentLineAllocationService_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform_operator.proto",
}
