// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type AgentLineAllocationInfo struct {
	AgentLineCode string `json:"agent_line_code"`
	Allocated     bool   `json:"allocated"`
	AllocatedAt   *int64 `json:"allocated_at,optional"`
}

type BasicResourceAllocationInfo struct {
	OperatorId     int64  `json:"operator_id"`
	OperatorCode   string `json:"operator_code"`
	OperatorName   string `json:"operator_name"`
	LanguageCount  int64  `json:"language_count"`
	RegionCount    int64  `json:"region_count"`
	AgentLineCount int64  `json:"agent_line_count"`
}

type BatchCreateOperatorGameCategoryItem struct {
	OpCode       string `json:"op_code"`
	CategoryCode string `json:"category_code"`
	Status       int32  `json:"status"`
}

type BatchCreateOperatorGameCategoryRequest struct {
	Items []BatchCreateOperatorGameCategoryItem `json:"items"`
}

type BatchCreateOperatorGameCategoryResponse struct {
	Total   int64 `json:"total"`
	Success int64 `json:"success"`
	Failed  int64 `json:"failed"`
}

type BatchCreateOperatorGameChannelItem struct {
	OpCode      string `json:"op_code"`
	ChannelCode string `json:"channel_code"`
	Status      int32  `json:"status"`
}

type BatchCreateOperatorGameChannelRequest struct {
	Items []BatchCreateOperatorGameChannelItem `json:"items"`
}

type BatchCreateOperatorGameChannelResponse struct {
	Total   int64 `json:"total"`
	Success int64 `json:"success"`
	Failed  int64 `json:"failed"`
}

type BatchCreateOperatorGameItem struct {
	OpCode   string `json:"op_code"`
	GameCode string `json:"game_code"`
	Name     string `json:"name"`
	Status   int32  `json:"status"`
}

type BatchCreateOperatorGameProviderItem struct {
	OpCode       string `json:"op_code"`
	ProviderCode string `json:"provider_code"`
	Status       int32  `json:"status"`
}

type BatchCreateOperatorGameProviderRequest struct {
	Items []BatchCreateOperatorGameProviderItem `json:"items"`
}

type BatchCreateOperatorGameProviderResponse struct {
	Total   int64 `json:"total"`
	Success int64 `json:"success"`
	Failed  int64 `json:"failed"`
}

type BatchCreateOperatorGameRequest struct {
	Items []BatchCreateOperatorGameItem `json:"items"`
}

type BatchCreateOperatorGameResponse struct {
	Total   int64 `json:"total"`
	Success int64 `json:"success"`
	Failed  int64 `json:"failed"`
}

type BatchDeleteOperatorGameCategoryRequest struct {
	Ids []int64 `json:"ids"`
}

type BatchDeleteOperatorGameCategoryResponse struct {
	Total   int64 `json:"total"`
	Success int64 `json:"success"`
	Failed  int64 `json:"failed"`
}

type BatchDeleteOperatorGameChannelRequest struct {
	Ids []int64 `json:"ids"`
}

type BatchDeleteOperatorGameChannelResponse struct {
	Total   int64 `json:"total"`
	Success int64 `json:"success"`
	Failed  int64 `json:"failed"`
}

type BatchDeleteOperatorGameProviderRequest struct {
	Ids []int64 `json:"ids"`
}

type BatchDeleteOperatorGameProviderResponse struct {
	Total   int64 `json:"total"`
	Success int64 `json:"success"`
	Failed  int64 `json:"failed"`
}

type BatchDeleteOperatorGameRequest struct {
	Ids []int64 `json:"ids"`
}

type BatchDeleteOperatorGameResponse struct {
	Total   int64 `json:"total"`
	Success int64 `json:"success"`
	Failed  int64 `json:"failed"`
}

type BatchUpdateOperatorGameCategoryStatusRequest struct {
	Ids    []int64 `json:"ids"`
	Status int32   `json:"status"`
}

type BatchUpdateOperatorGameCategoryStatusResponse struct {
	Total   int64 `json:"total"`
	Success int64 `json:"success"`
	Failed  int64 `json:"failed"`
}

type BatchUpdateOperatorGameChannelStatusRequest struct {
	Ids    []int64 `json:"ids"`
	Status int32   `json:"status"`
}

type BatchUpdateOperatorGameChannelStatusResponse struct {
	Total   int64 `json:"total"`
	Success int64 `json:"success"`
	Failed  int64 `json:"failed"`
}

type BatchUpdateOperatorGameProviderStatusRequest struct {
	Ids    []int64 `json:"ids"`
	Status int32   `json:"status"`
}

type BatchUpdateOperatorGameProviderStatusResponse struct {
	Total   int64 `json:"total"`
	Success int64 `json:"success"`
	Failed  int64 `json:"failed"`
}

type BatchUpdateOperatorGameStatusRequest struct {
	Ids    []int64 `json:"ids"`
	Status int32   `json:"status"`
}

type BatchUpdateOperatorGameStatusResponse struct {
	Total   int64 `json:"total"`
	Success int64 `json:"success"`
	Failed  int64 `json:"failed"`
}

type CompleteOperatorRequest struct {
	Id int64 `json:"id" validate:"required,gt=0"`
}

type CompleteOperatorResponse struct {
}

type CreateOperatorAdminRequest struct {
	OperatorId  int64  `json:"operator_id" validate:"required,gt=0"`
	Username    string `json:"username" validate:"required,notblank,max=64"`
	Password    string `json:"password" validate:"required,min=6,max=32"`
	DisplayName string `json:"display_name" validate:"required,notblank,max=100"`
	Status      *int64 `json:"status,optional" validate:"omitempty,oneof=1 2"`
}

type CreateOperatorAdminResponse struct {
	Id int64 `json:"id"`
}

type CreateOperatorDomainRequest struct {
	OperatorId int64   `json:"operator_id" validate:"required,gt=0"`
	DomainName string  `json:"domain_name" validate:"required,notblank,fqdn,max=253"`
	DomainType int64   `json:"domain_type" validate:"required,oneof=1 2 3"`
	Status     *int64  `json:"status,optional" validate:"omitempty,oneof=1 2"`
	Remark     *string `json:"remark,optional" validate:"omitempty,max=1000"`
}

type CreateOperatorDomainResponse struct {
	Id int64 `json:"id"`
}

type CreateOperatorProfileRequest struct {
	OperatorId   int64   `json:"operator_id" validate:"required,gt=0"`
	CompanyName  *string `json:"company_name,optional" validate:"omitempty,max=200"`
	ContactName  *string `json:"contact_name,optional" validate:"omitempty,max=100"`
	ContactEmail *string `json:"contact_email,optional" validate:"omitempty,email,max=255"`
	Remark       *string `json:"remark,optional" validate:"omitempty,max=1000"`
}

type CreateOperatorProfileResponse struct {
	Id int64 `json:"id"`
}

type CreateOperatorRequest struct {
	Name                   string  `json:"name" validate:"required,notblank,max=100"`
	TimezoneCode           string  `json:"timezone_code" validate:"required,notblank,max=64"`
	SettlementCurrencyCode string  `json:"settlement_currency_code" validate:"required,notblank,max=16"`
	Status                 *int64  `json:"status,optional" validate:"omitempty,oneof=1 2 3"`
	Remark                 *string `json:"remark,optional" validate:"omitempty,max=1000"`
}

type CreateOperatorResponse struct {
	Id   int64  `json:"id"`
	Code string `json:"code"`
}

type DeleteOperatorDomainRequest struct {
	Id int64 `json:"id" validate:"required,gt=0"`
}

type DeleteOperatorDomainResponse struct {
}

type DeleteOperatorRequest struct {
	Id int64 `json:"id" validate:"required,gt=0"`
}

type DeleteOperatorResponse struct {
}

type GetOperatorDomainRequest struct {
	Id int64 `form:"id" validate:"required,gt=0"`
}

type GetOperatorDomainResponse struct {
	OperatorDomainInfo
}

type GetOperatorGameCategoryListRequest struct {
	Page         int32  `form:"page,default=1"`
	PageSize     int32  `form:"page_size,default=10"`
	OpCode       string `form:"op_code,optional"`
	CategoryCode string `form:"category_code,optional"`
	Status       int32  `form:"status,optional"`
}

type GetOperatorGameCategoryListResponse struct {
	Items    []OperatorGameCategoryInfo `json:"items"`
	Total    int64                      `json:"total"`
	Page     int32                      `json:"page"`
	PageSize int32                      `json:"page_size"`
}

type GetOperatorGameChannelListRequest struct {
	Page        int32  `form:"page,default=1"`
	PageSize    int32  `form:"page_size,default=10"`
	OpCode      string `form:"op_code,optional"`
	ChannelCode string `form:"channel_code,optional"`
	Status      int32  `form:"status,optional"`
}

type GetOperatorGameChannelListResponse struct {
	Items    []OperatorGameChannelInfo `json:"items"`
	Total    int64                     `json:"total"`
	Page     int32                     `json:"page"`
	PageSize int32                     `json:"page_size"`
}

type GetOperatorGameListRequest struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"page_size,default=10"`
	OpCode   string `form:"op_code,optional"`
	GameCode string `form:"game_code,optional"`
	Status   int32  `form:"status,optional"`
}

type GetOperatorGameListResponse struct {
	Items    []OperatorGameInfo `json:"items"`
	Total    int64              `json:"total"`
	Page     int32              `json:"page"`
	PageSize int32              `json:"page_size"`
}

type GetOperatorGameProviderListRequest struct {
	Page         int32  `form:"page,default=1"`
	PageSize     int32  `form:"page_size,default=10"`
	OpCode       string `form:"op_code,optional"`
	ProviderCode string `form:"provider_code,optional"`
	Status       int32  `form:"status,optional"`
}

type GetOperatorGameProviderListResponse struct {
	Items    []OperatorGameProviderInfo `json:"items"`
	Total    int64                      `json:"total"`
	Page     int32                      `json:"page"`
	PageSize int32                      `json:"page_size"`
}

type GetOperatorProfileRequest struct {
	OperatorId int64 `form:"operator_id" validate:"required,gt=0"`
}

type GetOperatorProfileResponse struct {
	Profile *OperatorProfileInfo `json:"profile"`
}

type GetOperatorRequest struct {
	Id int64 `form:"id" validate:"required,gt=0"`
}

type GetOperatorResponse struct {
	OperatorInfo
}

type LanguageAllocationInfo struct {
	LanguageCode string `json:"language_code"`
	AllocatedAt  int64  `json:"allocated_at"`
}

type ListAgentLineAllocationsRequest struct {
	OperatorId int64 `form:"operator_id" validate:"required,gt=0"`
}

type ListAgentLineAllocationsResponse struct {
	List []AgentLineAllocationInfo `json:"list"`
}

type ListBasicResourceAllocationsRequest struct {
	PageRequest
	Keyword *string `form:"keyword,optional" validate:"omitempty,max=100"`
}

type ListBasicResourceAllocationsResponse struct {
	Total int64                         `json:"total"`
	List  []BasicResourceAllocationInfo `json:"list"`
}

type ListGameAllocationsRequest struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"page_size,default=10"`
	OpCode   string `form:"op_code,optional"`
	Status   int32  `form:"status,optional"`
}

type ListGameAllocationsResponse struct {
	Code     int32                        `json:"code"`
	Message  string                       `json:"message"`
	Items    []OperatorGameAllocationInfo `json:"items"`
	Total    int64                        `json:"total"`
	Page     int32                        `json:"page"`
	PageSize int32                        `json:"page_size"`
}

type ListLanguageAllocationsRequest struct {
	OperatorId int64 `form:"operator_id" validate:"required,gt=0"`
}

type ListLanguageAllocationsResponse struct {
	List []LanguageAllocationInfo `json:"list"`
}

type ListOperatorAdminsRequest struct {
	PageRequest
	OperatorId *int64  `form:"operator_id,optional" validate:"omitempty,gt=0"`
	Keyword    *string `form:"keyword,optional" validate:"omitempty,max=100"`
	Status     *int64  `form:"status,optional" validate:"omitempty,oneof=1 2"`
}

type ListOperatorAdminsResponse struct {
	Total int64               `json:"total"`
	List  []OperatorAdminInfo `json:"list"`
}

type ListOperatorDomainsRequest struct {
	PageRequest
	OperatorId *int64  `form:"operator_id,optional" validate:"omitempty,gt=0"`
	Keyword    *string `form:"keyword,optional" validate:"omitempty,max=253"`
	DomainType *int64  `form:"domain_type,optional" validate:"omitempty,oneof=1 2 3"`
	Status     *int64  `form:"status,optional" validate:"omitempty,oneof=1 2"`
}

type ListOperatorDomainsResponse struct {
	Total int64                `json:"total"`
	List  []OperatorDomainInfo `json:"list"`
}

type ListOperatorsRequest struct {
	PageRequest
	Keyword        *string `form:"keyword,optional" validate:"omitempty,max=100"`
	CreationStatus *int64  `form:"creation_status,optional" validate:"omitempty,oneof=1 2"`
	PublishStatus  *int64  `form:"publish_status,optional" validate:"omitempty,oneof=1 2 3 4"`
	Status         *int64  `form:"status,optional" validate:"omitempty,oneof=1 2 3"`
}

type ListOperatorsResponse struct {
	Total int64          `json:"total"`
	List  []OperatorInfo `json:"list"`
}

type ListRegionAllocationsRequest struct {
	OperatorId int64 `form:"operator_id" validate:"required,gt=0"`
}

type ListRegionAllocationsResponse struct {
	List []RegionAllocationInfo `json:"list"`
}

type OperatorAdminInfo struct {
	Id           int64  `json:"id"`
	OperatorId   int64  `json:"operator_id"`
	OperatorName string `json:"operator_name"`
	Username     string `json:"username"`
	DisplayName  string `json:"display_name"`
	Status       int64  `json:"status"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type OperatorDomainInfo struct {
	Id         int64   `json:"id"`
	OperatorId int64   `json:"operator_id"`
	DomainName string  `json:"domain_name"`
	DomainType int64   `json:"domain_type"`
	Status     int64   `json:"status"`
	Remark     *string `json:"remark,optional"`
	CreatedAt  int64   `json:"created_at"`
	UpdatedAt  int64   `json:"updated_at"`
}

type OperatorGameAllocationInfo struct {
	Id                int64  `json:"id"`
	OpCode            string `json:"op_code"`
	OpName            string `json:"op_name"`
	GameCount         int32  `json:"game_count"`
	GameCategoryCount int32  `json:"game_category_count"`
	GameProviderCount int32  `json:"game_provider_count"`
	GameChannelCount  int32  `json:"game_channel_count"`
	UpdatedAt         int64  `json:"updated_at"`
}

type OperatorGameCategoryInfo struct {
	Id           int64  `json:"id"`
	OpCode       string `json:"op_code"`
	CategoryCode string `json:"category_code"`
	Name         string `json:"name"`
	Status       int32  `json:"status"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type OperatorGameChannelInfo struct {
	Id          int64  `json:"id"`
	OpCode      string `json:"op_code"`
	ChannelCode string `json:"channel_code"`
	Name        string `json:"name"`
	Status      int32  `json:"status"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type OperatorGameInfo struct {
	Id        int64  `json:"id"`
	OpCode    string `json:"op_code"`
	GameCode  string `json:"game_code"`
	Name      string `json:"name"`
	Status    int32  `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type OperatorGameProviderInfo struct {
	Id           int64  `json:"id"`
	OpCode       string `json:"op_code"`
	ProviderCode string `json:"provider_code"`
	Name         string `json:"name"`
	Status       int32  `json:"status"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type OperatorInfo struct {
	Id                     int64   `json:"id"`
	Code                   string  `json:"code"`
	Name                   string  `json:"name"`
	TimezoneCode           string  `json:"timezone_code"`
	SettlementCurrencyCode string  `json:"settlement_currency_code"`
	CreationStatus         int64   `json:"creation_status"`
	PublishStatus          int64   `json:"publish_status"`
	Status                 int64   `json:"status"`
	Remark                 *string `json:"remark,optional"`
	PublishedAt            *int64  `json:"published_at,optional"`
	CreatedAt              int64   `json:"created_at"`
	UpdatedAt              int64   `json:"updated_at"`
}

type OperatorProfileInfo struct {
	Id           int64   `json:"id"`
	OperatorId   int64   `json:"operator_id"`
	CompanyName  *string `json:"company_name,optional"`
	ContactName  *string `json:"contact_name,optional"`
	ContactEmail *string `json:"contact_email,optional"`
	Remark       *string `json:"remark,optional"`
	CreatedAt    int64   `json:"created_at"`
	UpdatedAt    int64   `json:"updated_at"`
}

type PageRequest struct {
	Page     int64 `form:"page" validate:"required,gte=1"`
	PageSize int64 `form:"page_size" validate:"required,gte=1,lte=100"`
}

type PingResponse struct {
}

type PublishOperatorRequest struct {
	Id int64 `json:"id" validate:"required,gt=0"`
}

type PublishOperatorResponse struct {
}

type RegionAllocationInfo struct {
	RegionCode  string `json:"region_code"`
	AllocatedAt int64  `json:"allocated_at"`
}

type ResetOperatorAdminPasswordRequest struct {
	Id       int64  `json:"id" validate:"required,gt=0"`
	Password string `json:"password" validate:"required,min=6,max=32"`
}

type ResetOperatorAdminPasswordResponse struct {
}

type SaveAgentLineAllocationsRequest struct {
	OperatorId     int64    `json:"operator_id" validate:"required,gt=0"`
	AgentLineCodes []string `json:"agent_line_codes" validate:"omitempty,dive,required,notblank,max=32"`
}

type SaveAgentLineAllocationsResponse struct {
}

type SaveLanguageAllocationsRequest struct {
	OperatorId    int64    `json:"operator_id" validate:"required,gt=0"`
	LanguageCodes []string `json:"language_codes" validate:"omitempty,dive,required,notblank,max=16"`
}

type SaveLanguageAllocationsResponse struct {
}

type SaveRegionAllocationsRequest struct {
	OperatorId  int64    `json:"operator_id" validate:"required,gt=0"`
	RegionCodes []string `json:"region_codes" validate:"omitempty,dive,required,notblank,len=2"`
}

type SaveRegionAllocationsResponse struct {
}

type UpdateOperatorAdminRequest struct {
	Id          int64   `json:"id" validate:"required,gt=0"`
	Username    *string `json:"username,optional" validate:"omitempty,notblank,max=64"`
	Password    *string `json:"password,optional" validate:"omitempty,min=6,max=32"`
	DisplayName *string `json:"display_name,optional" validate:"omitempty,notblank,max=100"`
	Status      *int64  `json:"status,optional" validate:"omitempty,oneof=1 2"`
}

type UpdateOperatorAdminResponse struct {
}

type UpdateOperatorAdminStatusRequest struct {
	Id     int64 `json:"id" validate:"required,gt=0"`
	Status int64 `json:"status" validate:"required,oneof=1 2"`
}

type UpdateOperatorAdminStatusResponse struct {
}

type UpdateOperatorDomainRequest struct {
	Id         int64   `json:"id" validate:"required,gt=0"`
	DomainName *string `json:"domain_name,optional" validate:"omitempty,notblank,fqdn,max=253"`
	DomainType *int64  `json:"domain_type,optional" validate:"omitempty,oneof=1 2 3"`
	Status     *int64  `json:"status,optional" validate:"omitempty,oneof=1 2"`
	Remark     *string `json:"remark,optional" validate:"omitempty,max=1000"`
}

type UpdateOperatorDomainResponse struct {
}

type UpdateOperatorProfileRequest struct {
	OperatorId   int64   `json:"operator_id" validate:"required,gt=0"`
	CompanyName  *string `json:"company_name,optional" validate:"omitempty,max=200"`
	ContactName  *string `json:"contact_name,optional" validate:"omitempty,max=100"`
	ContactEmail *string `json:"contact_email,optional" validate:"omitempty,email,max=255"`
	Remark       *string `json:"remark,optional" validate:"omitempty,max=1000"`
}

type UpdateOperatorProfileResponse struct {
}

type UpdateOperatorRequest struct {
	Id                     int64   `json:"id" validate:"required,gt=0"`
	Name                   *string `json:"name,optional" validate:"omitempty,notblank,max=100"`
	TimezoneCode           *string `json:"timezone_code,optional" validate:"omitempty,notblank,max=64"`
	SettlementCurrencyCode *string `json:"settlement_currency_code,optional" validate:"omitempty,notblank,max=16"`
	Status                 *int64  `json:"status,optional" validate:"omitempty,oneof=1 2 3"`
	Remark                 *string `json:"remark,optional" validate:"omitempty,max=1000"`
}

type UpdateOperatorResponse struct {
}
