syntax = "proto3";

package vendors;

option go_package = "oa.98ent.com/p9/platform-game/rpc/pb/vendors";

import "google/protobuf/empty.proto";

// ===============================
// 游戏渠道
// ===============================

// GameChannelInfo 游戏渠道（来自 game-vendor-gateway 返回值）
message GameChannelInfo {
  int64 id = 1;
  string code = 2;
  string name = 3;
  string currency = 4;
  int64 weight = 5;
  uint32 status = 6;        // 1.Normal 2.Disabled
  map<string, string> extra = 7;
  uint32 update_utype = 8;
  int64 update_uid = 9;
  int64 updates = 10;
  int64 update_at = 11;
  uint32 create_utype = 12;
  int64 create_uid = 13;
  int64 create_at = 14;
  uint32 load_type = 15;    // GameLoadType 1.Embed 2.Ext link
}

// GameChannelDeletedInfo 游戏渠道删除记录
message GameChannelDeletedInfo {
  int64 id = 1;
  string code = 2;
  string name = 3;
  string currency = 4;
  int64 weight = 5;
  uint32 status = 6;        // 1.Normal 2.Disabled
  map<string, string> extra = 7;
  uint32 update_utype = 8;
  int64 update_uid = 9;
  int64 updates = 10;
  int64 update_at = 11;
  uint32 create_utype = 12;
  int64 create_uid = 13;
  int64 create_at = 14;
  uint32 delete_utype = 15;  // 删除人类型：1.系统用户 2.合作商用户 3.代理用户 4.游戏用户
  int64  delete_uid = 16;    // 删除人ID
  string delete_notes = 17;  // 删除备注
  int64  delete_at = 18;     // 删除时间
  uint32 load_type = 19;     // GameLoadType 1.Embed 2.Ext link
}

// GetChannelResponse 获取游戏渠道列表响应
message GetChannelResponse {
  int64 code = 1;
  string msg = 2;
  repeated GameChannelInfo channel_list = 3;
}

// GetChannelDeletedResponse 获取已删除游戏渠道列表响应
message GetChannelDeletedResponse {
  int64 code = 1;
  string msg = 2;
  repeated GameChannelDeletedInfo channel_list = 3;
}
