syntax = "proto3";

package platform_game;

option go_package = "oa.98ent.com/p9/platform-game/rpc/pb/platform_game";

// ProviderInfo 供应商信息
message ProviderInfo {
    int64 id = 1;
    int64 source_id = 2;
    string provider_code = 3;
    string source_provider_code = 4;
    string name_key = 5;
    string logo_url = 6;
    string source_logo_url = 7;
    int32 sort_no = 8;
    int32 status = 9;
    int32 source_status = 10;
    int32 is_deleted = 11;
    int64 created_at = 12;
    int64 updated_at = 13;
}

// GetGameProviderListRequest 获取游戏供应商列表请求
message GetGameProviderListRequest {
    int32 page = 1;
    int32 page_size = 2;
    string provider_code = 3;
    int32 status = 4;
    int32 is_deleted = 5;
}

// GetGameProviderListResp 游戏供应商列表响应
message GetGameProviderListResp {
    int32 code = 1;
    string message = 2;
    repeated ProviderInfo items = 3;
    int64 total = 4;
}

// GetGameProviderRequest 获取单个游戏供应商请求
message GetGameProviderRequest {
    int64 id = 1;
}

// GetGameProviderResp 获取单个游戏供应商响应
message GetGameProviderResp {
    int32 code = 1;
    string message = 2;
    ProviderInfo data = 3;
}

// UpdateGameProviderRequest 更新供应商请求
message UpdateGameProviderRequest {
    int64 id = 1;
    int32 sort_no = 2;
    int32 status = 3;
    string logo_url = 4;
    bool force_logout = 5;
}

// UpdateGameProviderResp 更新供应商响应
message UpdateGameProviderResp {
    int32 code = 1;
    string message = 2;
    ProviderInfo data = 3;
}
